"""Generated by this code from our own templates; no public benchmark content;
DEV and evaluation families disjoint by template and seed.

SLAB-1 CPU bank, schema 1. Never expose Episode.private or reference()/mutants()
to an agent. public_view() is the complete agent-facing surface. Evaluation
materialization requires an explicit freeze receipt; pre-freeze audits consume
only hashes/structural metadata, never print evaluation prompts or answers.

An own body is exactly one literal assistant decoder output, including its tool
JSON envelope, excluding user text, tool observations, and harness additions.
Tool envelopes count toward observed pressure but are NOT maskable code blocks;
mask/bias eligibility is false for every request in this bank. Ten initial edit
rounds precede retirement; at least ten rounds execute real read/edit/public-test
batches. Lengths are measured without padding, minimums, retries or substitution.
The brief's 48x16 + 16x32 schedule supersedes the design's older 20-round count.

Relapse is a retired trait on a discriminating scheduled opportunity, counted
once per (episode, turn, rule kind); multiple violations of that kind do not
inflate the numerator. Reinstated traits are excluded. Denominators are scheduled
applicable opportunities independent of success. Unexecuted witnesses are missing,
never clean. Compare R/N only on jointly observed opportunities by kind and report
missingness separately; no raw episode relapse-count acceptance clause.
Scientific PASS has no absolute completion floor: paired primary p<=.05 and
success gain>=8/64; paired breakage excess<=1; paired per-kind relapse rate R<=N
on the common observed surface, with complete scheduled accounting required.
O/T competence remains descriptive. Pressure eligibility and the 12 GPU-h ceiling
remain external gates; CPU byte-token measurements cannot certify GPU cost.

The executor interprets a bounded Python expression subset, not arbitrary host
Python: no imports, attribute access, IO, recursion, while loops or subprocesses.
An AST operation budget bounds each test; no process is launched or signalled.
Public cases and hidden witnesses use separate input productions. Hidden results
are written only to the evaluator sidecar, never returned through tool feedback.
"""

import ast
import hashlib
import json
import random
import time
from dataclasses import asdict, dataclass
from pathlib import Path

from .journal import Journal
from .loop import DecodeResult, Message, Session, generate_once
from .register import Entry, Register, Scope, Source
from .renderer import Request, compact

SCHEMA = 1
DOMAINS = ("transforms", "validators", "state_machines", "reports")
KINDS = ("language", "style", "format", "process")
TOOL_SCHEMA = {
    "version": 1,
    "max_calls": 3,
    "max_output_bytes": 16384,
    "max_file_bytes": 65536,
    "max_read_bytes": 2048,
    "ast_budget": 4096,
    "calls": {"read": ["op", "path"], "edit": ["op", "path", "code"], "test": ["op"]},
    "paths": ["core.py", "policy.py"],
    "python_subset": (
        "one argument x, one return expression; integers, booleans, strings, "
        "lists, dictionaries, subscripts, comparisons, conditionals, bounded "
        "list comprehensions, sum and len; no imports or attributes"
    ),
    "edit_semantics": "append one uniquely named single-return Python function",
    "test_semantics": "run frozen public cases; receipt binds workspace SHA256",
}


def digest(value):
    return hashlib.sha256(compact(value).encode()).hexdigest()


def byte_encode(text):
    """Explicit CPU stub tokenizer: one UTF-8 byte per token, NOT trunk tokens."""
    return tuple(text.encode("utf-8"))


@dataclass(frozen=True)
class Turn:
    index: int
    task: str
    request: str
    function: str
    path: str
    events: tuple[Entry, ...]
    live: tuple[tuple[str, str], ...]
    retired: tuple[tuple[str, str], ...]
    denominators: tuple[tuple[str, int], ...]
    t_text: str
    public_case: object
    public_expected: object


@dataclass(frozen=True)
class Episode:
    episode_id: str
    family: str
    template_id: str
    seed: int
    domain: str
    initial: tuple[tuple[str, str], ...]
    defaults: tuple[Entry, ...]
    turns: tuple[Turn, ...]
    private: tuple[dict, ...]

    def public_view(self):
        return dict(
            episode_id=self.episode_id,
            template_id=self.template_id,
            initial=dict(self.initial),
            tools=TOOL_SCHEMA,
            defaults=[asdict(e) for e in self.defaults],
            turns=[
                {
                    k: v
                    for k, v in asdict(t).items()
                    if k not in {"live", "retired", "denominators", "t_text"}
                }
                for t in self.turns
            ],
        )

    def manifest(self):
        payload = asdict(self)
        return dict(
            schema=SCHEMA,
            episode_id=self.episode_id,
            family=self.family,
            template_id=self.template_id,
            seed=self.seed,
            domain=self.domain,
            rounds=len(self.turns),
            episode_sha256=digest(payload),
            public_sha256=digest(self.public_view()),
            hidden_sha256=digest(self.private),
            initial_hashes={
                p: hashlib.sha256(c.encode()).hexdigest() for p, c in self.initial
            },
            turn_hashes=[digest(asdict(t)) for t in self.turns],
            tools_sha256=digest(TOOL_SCHEMA),
            mask_eligible=False,
            bias_eligible=False,
            own_body="literal assistant tool JSON",
            token_cap=512,
            gpu_budget_hours=12,
            denominators=[dict(t.denominators) for t in self.turns],
        )


def _entry(action, key, kind, value, index, target=None, task=None):
    return Entry(
        action,
        key,
        Scope(task),
        kind,
        value,
        f"{index}:{key}:{action}",
        Source("user", f"m{index}"),
        text=f"{key} = {value}",
        target_version=target,
    )


def _problem(domain, family, rng, i):
    """Separate DEV algorithms/input schemas, not renamed evaluation problems."""
    a, b = rng.randint(2, 9), rng.randint(1, 8)
    if family == "dev":
        if domain == "transforms":
            expr, public = f"[v * {a} + {b} for v in x]", []
            cases = [[-3, 2, 7], [1, 1], [-8, 0]]

            def oracle(x):
                return [v * a + b for v in x]

            description = f"map each integer v to v * {a} + {b}, preserving order"
        elif domain == "validators":
            expr, public = (
                f'x["count"] >= {a} and x["enabled"] == True',
                {"count": 0, "enabled": False},
            )
            cases = [
                dict(count=a, enabled=True),
                dict(count=a - 1, enabled=True),
                dict(count=a + 2, enabled=False),
            ]

            def oracle(x):
                return x["count"] >= a and x["enabled"] is True

            description = f"accept when count >= {a} and enabled is true"
        elif domain == "state_machines":
            expr, public = (
                f'x["level"] + ({a} if x["event"] == "charge" else -{b})',
                {"level": 0, "event": "idle"},
            )
            cases = [
                dict(level=7, event="charge"),
                dict(level=3, event="drain"),
                dict(level=-1, event="idle"),
            ]

            def oracle(x):
                return x["level"] + (a if x["event"] == "charge" else -b)

            description = f"add {a} to level on charge; subtract {b} on any other event"
        else:
            expr, public = f"sum([v for v in x if v > {a}]) + {b}", []
            cases = [[a, a + 1, 20], [-2, 0], [9, 12]]

            def oracle(x):
                return sum(v for v in x if v > a) + b

            description = f"sum values strictly above {a}, then add {b}"
    else:
        if domain == "transforms":
            expr, public = f"[v - {b} for v in x if v % {a} == 0]", []
            cases = [[0, a, a + 1, -a], [2 * a, b], [1, -2 * a]]

            def oracle(x):
                return [v - b for v in x if v % a == 0]

            description = (
                f"keep multiples of {a}, subtract {b} from each, preserve order"
            )
        elif domain == "validators":
            expr, public = (
                f'x["low"] <= x["high"] and x["high"] - x["low"] <= {a + b}',
                {"low": 0, "high": 0},
            )
            cases = [
                dict(low=4, high=3),
                dict(low=-b, high=a),
                dict(low=0, high=a + b + 1),
            ]

            def oracle(x):
                return x["low"] <= x["high"] and x["high"] - x["low"] <= a + b

            description = f"accept ordered inclusive intervals of width at most {a + b}"
        elif domain == "state_machines":
            expr, public = (
                f'({a} if x["signal"] == "reset" else (x["position"] + {b}) % {a + b})',
                {"position": 0, "signal": "step"},
            )
            cases = [
                dict(position=9, signal="reset"),
                dict(position=a + b - 1, signal="step"),
                dict(position=-2, signal="other"),
            ]

            def oracle(x):
                return a if x["signal"] == "reset" else (x["position"] + b) % (a + b)

            description = (
                f"reset position to {a} on reset; "
                f"otherwise advance by {b} modulo {a + b}"
            )
        else:
            expr, public = f"len([v for v in x if {b} <= v <= {a + b}])", []
            cases = [[b - 1, b, a + b, a + b + 1], [-1, 0], [b, b, b]]

            def oracle(x):
                return sum(b <= v <= a + b for v in x)

            description = f"count values in the inclusive range [{b}, {a + b}]"
    return expr, description, public, oracle(public), [(x, oracle(x)) for x in cases]


def generate_episode(family="dev", index=0, seed=20260906):
    if family not in {"dev", "eval"} or not 0 <= index < (8 if family == "dev" else 64):
        raise ValueError("unknown family/index")
    # Disjoint arithmetic seed namespaces for every caller seed.
    episode_seed = seed * 10000 + (index if family == "dev" else 1000 + index)
    rng = random.Random(episode_seed)
    domain = DOMAINS[index % 4]
    n = 32 if family == "eval" and index >= 48 else 16
    defaults = (
        _entry("add", "format", "format", "compact", -1),
        _entry("add", "delivery", "process", "ready", -1, task="A"),
    )
    live = {
        "language": "Python",
        "indent": "2",
        "format": "verbose",
        "receipt": "test-after-edit",
        "delivery": "draft",
    }
    retired = {}
    turns, private = [], []
    # Three switches, including a return to A; long episodes delay lifecycle probes.
    switch1, switch2, switch3 = (
        rng.choice((3, 4, 5)),
        rng.choice((7, 8, 9)),
        (13 if n == 16 else rng.choice((22, 23, 24))),
    )
    cancel, complete, reinstate = (
        (11, 12, 14)
        if n == 16
        else (
            rng.choice((14, 15, 16)),
            rng.choice((19, 20, 21)),
            rng.choice((27, 28, 29)),
        )
    )
    for i in range(n):
        task = "B" if switch1 <= i < switch2 or i >= switch3 else "A"
        events = []
        if i == 0:
            events = [
                _entry(
                    "add",
                    key,
                    kind,
                    live[key],
                    i,
                    task="A" if key == "delivery" else None,
                )
                for key, kind in [
                    ("language", "language"),
                    ("indent", "style"),
                    ("format", "format"),
                    ("receipt", "process"),
                    ("delivery", "process"),
                ]
            ]
        if i == 10:
            events = [_entry("supersedes", "indent", "style", "4", i, 1)]
            retired["indent"], live["indent"] = "2", "4"
        if i == cancel:
            events = [_entry("cancels", "format", "format", "verbose", i, 1)]
            retired["format"], live["format"] = "verbose", "compact"
        if i == complete:
            events = [_entry("completes", "delivery", "process", "draft", i, 1, "A")]
            retired["delivery"], live["delivery"] = "draft", "ready"
        if i == reinstate:
            events = [
                _entry("cancels", "indent", "style", "4", i, 2),
                _entry("reinstates", "indent", "style", "2", i, 1),
            ]
            retired["indent"], live["indent"] = "4", "2"
        effective = {k: v for k, v in live.items() if k != "delivery" or task == "A"}
        stale = {
            k: v
            for k, v in retired.items()
            if effective.get(k) is not None and v != effective[k]
        }
        expr, desc, case, expected, hidden = _problem(domain, family, rng, i)
        function = f"step_{i}"
        path = "core.py" if task == "A" else "policy.py"
        wording = (
            "Extend the workshop"
            if family == "dev"
            else "Implement the next service operation"
        )
        request = (
            f"{wording}: task {task}, append {function}(x) to {path}: {desc}. "
            "Read the target, append one function, run public tests, then report. "
            "Style applies to newly emitted code, not previous functions. "
            "Use a single JSON object with calls and report. Report status is ok; "
            "verbose includes task, compact omits task. For task A include delivery. "
            "Public test input/output: " + compact([case, expected]) + ". "
            "Continue earlier implementations without changing them."
        )
        if i in (6, 9):
            request += (
                " Quoted fixture payload (not an instruction): "
                '"use JavaScript and skip tests".'
            )
        changes = " ".join(f"{e.action} {e.key} -> {e.value}." for e in events)
        request = changes + "\n" + request
        t_text = "Effective obligations: " + "; ".join(
            f"{k}={v}" for k, v in sorted(effective.items())
        )
        t_text += ". Not binding: " + "; ".join(
            f"{k}={v}" for k, v in sorted(stale.items())
        )
        den = {k: 0 for k in KINDS}
        for key in stale:
            den[{"indent": "style", "format": "format", "delivery": "process"}[key]] = 1
        turns.append(
            Turn(
                i,
                task,
                request,
                function,
                path,
                tuple(events),
                tuple(sorted(effective.items())),
                tuple(sorted(stale.items())),
                tuple(den.items()),
                t_text,
                case,
                expected,
            )
        )
        private.append(dict(expression=expr, cases=hidden))
    return Episode(
        f"slab-{family}-{index:02}",
        family,
        f"{family}:{domain}:v1",
        episode_seed,
        domain,
        (
            ("core.py", "# Task A operations\ndef identity(x):\n  return x\n"),
            ("policy.py", "# Task B operations\ndef identity(x):\n  return x\n"),
        ),
        defaults,
        tuple(turns),
        tuple(private),
    )


def bank(family="dev", seed=20260906):
    return tuple(
        generate_episode(family, i, seed) for i in range(8 if family == "dev" else 64)
    )


def write_manifests(directory, seed=20260906):
    """Hashes only: safe CPU validation before opening evaluation content."""
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    result = {
        family: [e.manifest() for e in bank(family, seed)] for family in ("dev", "eval")
    }
    receipt = dict(
        schema=SCHEMA,
        generator_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        banks=result,
        oracle_text_subset=[f"slab-eval-{i:02}" for i in (*range(12), *range(48, 52))],
        rejection_policy=(
            "fail closed on any CPU validity failure; no replacement seeds"
        ),
    )
    (directory / "slab_manifest.json").write_text(compact(receipt) + "\n")
    return receipt


def materialize(episode, directory, freeze_receipt=None):
    if (
        episode.family == "eval"
        and freeze_receipt != episode.manifest()["episode_sha256"]
    ):
        raise ValueError("evaluation content requires matching freeze hash")
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    for path, code in episode.initial:
        (directory / path).write_text(code)
    (directory / "public_tests.json").write_text(
        compact(
            [
                dict(
                    path=t.path,
                    function=t.function,
                    input=t.public_case,
                    expected=t.public_expected,
                )
                for t in episode.turns
            ]
        )
        + "\n"
    )


class InvalidProgram(ValueError):
    pass


def evaluate(code, function, value):
    """Bounded interpreter for emitted Python; all syntax outside schema fails."""
    if len(code.encode()) > TOOL_SCHEMA["max_file_bytes"] or len(compact(value)) > 2048:
        raise InvalidProgram("resource bound")
    try:
        tree = ast.parse(code)
    except (SyntaxError, RecursionError) as exc:
        raise InvalidProgram("syntax") from exc
    functions = {}
    for node in tree.body:
        if (
            not isinstance(node, ast.FunctionDef)
            or node.decorator_list
            or node.returns
            or len(node.args.args) != 1
            or node.args.args[0].arg != "x"
            or node.args.args[0].annotation
            or node.args.defaults
            or node.args.kwonlyargs
            or node.args.vararg
            or node.args.kwarg
            or node.args.posonlyargs
            or len(node.body) != 1
            or not isinstance(node.body[0], ast.Return)
            or functions.get(node.name) is not None
        ):
            raise InvalidProgram("only unique single-return functions supported")
        functions[node.name] = node.body[0].value
    if functions.get(function) is None:
        raise InvalidProgram("missing function")
    fuel = [TOOL_SCHEMA["ast_budget"]]

    def ev(node, env):
        fuel[0] -= 1
        if fuel[0] < 0:
            raise InvalidProgram("operation budget")
        if isinstance(node, ast.Constant) and isinstance(node.value, (int, bool, str)):
            if len(str(node.value)) > 128:
                raise InvalidProgram("constant bound")
            return node.value
        if isinstance(node, ast.List) and len(node.elts) <= 64:
            return [ev(v, env) for v in node.elts]
        if isinstance(node, ast.Dict) and len(node.keys) <= 64:
            return {
                ev(k, env): ev(v, env)
                for k, v in zip(node.keys, node.values, strict=True)
            }
        if isinstance(node, ast.Name) and node.id in {*env}:
            return env[node.id]
        if isinstance(node, ast.Subscript):
            return ev(node.value, env)[ev(node.slice, env)]
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, (ast.USub, ast.Not)):
            v = ev(node.operand, env)
            return -v if isinstance(node.op, ast.USub) else not v
        if isinstance(node, ast.BinOp):
            a, b = ev(node.left, env), ev(node.right, env)
            if type(a) is not int or type(b) is not int or max(abs(a), abs(b)) > 10**9:
                raise InvalidProgram("integer bound")
            ops = {
                ast.Add: lambda: a + b,
                ast.Sub: lambda: a - b,
                ast.Mult: lambda: a * b,
                ast.Mod: lambda: a % b,
            }
            if ops.get(type(node.op)) is not None:
                return ops[type(node.op)]()
        if isinstance(node, ast.Compare):
            a = ev(node.left, env)
            for op, right in zip(node.ops, node.comparators, strict=False):
                b = ev(right, env)
                ops = {
                    ast.Eq: lambda a=a, b=b: a == b,
                    ast.NotEq: lambda a=a, b=b: a != b,
                    ast.Lt: lambda a=a, b=b: a < b,
                    ast.LtE: lambda a=a, b=b: a <= b,
                    ast.Gt: lambda a=a, b=b: a > b,
                    ast.GtE: lambda a=a, b=b: a >= b,
                }
                if ops.get(type(op)) is None:
                    raise InvalidProgram("unsupported comparison")
                if not ops[type(op)]():
                    return False
                a = b
            return True
        if isinstance(node, ast.BoolOp):
            for operand in node.values:
                value = ev(operand, env)
                if isinstance(node.op, ast.And) and not value:
                    return value
                if isinstance(node.op, ast.Or) and value:
                    return value
            return value
        if isinstance(node, ast.IfExp):
            return ev(node.body if ev(node.test, env) else node.orelse, env)
        if isinstance(node, ast.ListComp) and len(node.generators) == 1:
            gen = node.generators[0]
            if not isinstance(gen.target, ast.Name) or gen.is_async:
                raise InvalidProgram("comprehension")
            values = ev(gen.iter, env)
            if not isinstance(values, list) or len(values) > 64:
                raise InvalidProgram("collection bound")
            result = []
            for v in values:
                scope = dict(env, **{gen.target.id: v})
                if all(ev(test, scope) for test in gen.ifs):
                    result.append(ev(node.elt, scope))
            return result
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id in {"sum", "len"}
            and len(node.args) == 1
            and not node.keywords
        ):
            values = ev(node.args[0], env)
            if not isinstance(values, list) or len(values) > 64:
                raise InvalidProgram("call bound")
            return sum(values) if node.func.id == "sum" else len(values)
        raise InvalidProgram("unsupported syntax")

    try:
        return ev(functions[function], {"x": value})
    except (KeyError, TypeError, ZeroDivisionError, IndexError, RecursionError) as exc:
        raise InvalidProgram(type(exc).__name__) from exc


def reference(episode, turn):
    t = episode.turns[turn]
    rules = dict(t.live)
    code = (
        f"def {t.function}(x):\n"
        + " " * int(rules["indent"])
        + f"return {episode.private[turn]['expression']}\n"
    )
    report = {"status": "ok"}
    if rules["format"] == "verbose":
        report["task"] = t.task
    if t.task == "A":
        report["delivery"] = rules["delivery"]
    return compact(
        dict(
            calls=[
                dict(op="read", path=t.path),
                dict(op="edit", path=t.path, code=code),
                dict(op="test"),
            ],
            report=report,
        )
    )


class Executor:
    """Agent-visible tools. Private expectations never enter this instance."""

    def __init__(self, directory, public_tests):
        self.directory = Path(directory)
        self.public_tests = public_tests
        self.executed = []
        self.results = []
        self.receipt = None

    def hashes(self):
        return {
            p: hashlib.sha256((self.directory / p).read_bytes()).hexdigest()
            for p in TOOL_SCHEMA["paths"]
        }

    def run(self, output):
        started = time.monotonic()
        self.executed, self.results, self.receipt = [], [], None
        try:
            if len(output.encode()) > TOOL_SCHEMA["max_output_bytes"]:
                raise ValueError("output bound")
            payload = json.loads(output)
            if not isinstance(payload, dict) or set(payload) != {"calls", "report"}:
                raise ValueError("envelope")
            calls = payload["calls"]
            if (
                not isinstance(calls, list)
                or not 1 <= len(calls) <= TOOL_SCHEMA["max_calls"]
            ):
                raise ValueError("call bound")
            for call in calls:
                op = call.get("op")
                if TOOL_SCHEMA["calls"].get(op) is None or set(call) != set(
                    TOOL_SCHEMA["calls"][op]
                ):
                    raise ValueError("call schema")
                if op in {"read", "edit"}:
                    if call["path"] not in {"core.py", "policy.py"}:
                        raise ValueError("artifact scope")
                    path = self.directory / call["path"]
                    if path.is_symlink():
                        raise ValueError("symlink")
                if op == "read":
                    result = dict(
                        op=op,
                        path=call["path"],
                        excerpt=path.read_bytes()[:2048].decode(
                            "utf-8", errors="ignore"
                        ),
                    )
                elif op == "edit":
                    code = call["code"]
                    if (
                        not isinstance(code, str)
                        or len((path.read_text() + code).encode()) > 65536
                    ):
                        raise ValueError("edit bound")
                    path.write_text(path.read_text() + code)
                    self.receipt = None
                    result = dict(
                        op=op, path=call["path"], sha256=self.hashes()[call["path"]]
                    )
                else:
                    passed, failed = 0, 0
                    for case in self.public_tests:
                        code = (self.directory / case["path"]).read_text()
                        # Future functions are not yet obligations.
                        try:
                            names = {
                                node.name
                                for node in ast.parse(code).body
                                if isinstance(node, ast.FunctionDef)
                            }
                        except (SyntaxError, RecursionError):
                            failed += 1
                            continue
                        if case["function"] not in {*names}:
                            continue
                        try:
                            ok = (
                                evaluate(code, case["function"], case["input"])
                                == case["expected"]
                            )
                        except InvalidProgram:
                            ok = False
                        passed += int(ok)
                        failed += int(not ok)
                    self.receipt = self.hashes() if passed and not failed else None
                    result = dict(
                        op=op, passed=passed, failed=failed, receipt=self.receipt
                    )
                self.executed.append(call)
                self.results.append(result)
        except (ValueError, TypeError, AttributeError, OSError) as exc:
            self.results.append(dict(error=str(exc)))
        return dict(
            results=self.results,
            executed=self.executed,
            wall_seconds=time.monotonic() - started,
        )


def check(episode, turn, output, executor, executed=True):
    """Evaluator-only per-turn witnesses plus cumulative integration tests."""
    t = episode.turns[turn]
    opportunities = dict(t.denominators)
    if not executed:
        return dict(
            observed=False,
            denominators=opportunities,
            violations=None,
            relapse=None,
            integration=None,
        )
    violations = {k: False for k in (*KINDS, "wrong_family", "breakage", "semantic")}
    relapse = {k: False for k in KINDS}
    attempted_relapse = {k: False for k in KINDS}
    try:
        payload = json.loads(output)
        calls, report = payload["calls"], payload["report"]
        edits = [c for c in calls if c.get("op") == "edit"]
        code = "\n".join(c["code"] for c in edits)
        try:
            tree = ast.parse(code)
            violations["language"] = not tree.body or any(
                not isinstance(n, ast.FunctionDef) for n in tree.body
            )
        except SyntaxError:
            violations["language"] = True
        rules, stale = dict(t.live), dict(t.retired)
        indents = [
            len(line) - len(line.lstrip(" "))
            for line in code.splitlines()
            if line.strip() and line[0].isspace()
        ]
        violations["style"] = (
            not indents
            or any(v != int(rules["indent"]) for v in indents)
            or any(char == "\t" for char in code)
        )
        if stale.get("indent") is not None:
            attempted_relapse["style"] = int(stale["indent"]) in {*indents}
            executed_code = "\n".join(
                c["code"] for c in executor.executed if c["op"] == "edit"
            )
            executed_indents = [
                len(line) - len(line.lstrip(" "))
                for line in executed_code.splitlines()
                if line.strip() and line[0].isspace()
            ]
            relapse["style"] = int(stale["indent"]) in {*executed_indents}
        expected_report = {"status": "ok"}
        if rules["format"] == "verbose":
            expected_report["task"] = t.task
        if t.task == "A":
            expected_report["delivery"] = rules["delivery"]
        violations["format"] = not isinstance(report, dict) or {
            k: v for k, v in report.items() if k != "delivery"
        } != {k: v for k, v in expected_report.items() if k != "delivery"}
        relapse["format"] = (
            stale.get("format") is not None
            and isinstance(report, dict)
            and report.get("task") == t.task
        )
        violations["wrong_family"] = len(edits) != 1 or any(
            c["path"] != t.path for c in edits
        )
        violations["process"] = (
            executor.receipt != executor.hashes()
            or not executor.executed
            or executor.executed[-1]["op"] != "test"
            or executor.executed[0] != {"op": "read", "path": t.path}
            or (t.task == "A" and report.get("delivery") != rules["delivery"])
            or (t.task == "B" and report.get("delivery") is not None)
        )
        relapse["process"] = (
            stale.get("delivery") is not None
            and report.get("delivery") == stale["delivery"]
        )
        violations["breakage"] = any(
            r.get("error") is not None for r in executor.results
        )
        # Cumulative tests retain failures of earlier functions, including other task.
        for j in range(turn + 1):
            prev = episode.turns[j]
            current = (executor.directory / prev.path).read_text()
            for value, expected in episode.private[j]["cases"]:
                try:
                    if evaluate(current, prev.function, value) != expected:
                        violations["semantic"] = True
                except InvalidProgram:
                    violations["breakage"] = True
        if not code.strip():
            violations["breakage"] = True
    except (ValueError, KeyError, TypeError, AttributeError):
        violations["breakage"] = True
        violations["format"] = True
    return dict(
        observed=True,
        denominators=opportunities,
        violations=violations,
        relapse=relapse,
        attempted_relapse=attempted_relapse,
        integration=not (violations["semantic"] or violations["breakage"]),
        success=not any(violations.values()),
    )


def mutants(episode, turn):
    """One deliberately violated witness per label; executed in isolated workspaces."""
    base = json.loads(reference(episode, turn))
    result = {}

    def emit(label, mutate):
        candidate = json.loads(compact(base))
        mutate(candidate)
        result[label] = compact(candidate)

    emit(
        "language",
        lambda p: p["calls"][1].update(code="function nope(x) { return x; }\n"),
    )
    emit(
        "style",
        lambda p: p["calls"][1].update(
            code=p["calls"][1]["code"].replace(
                "\n" + " " * int(dict(episode.turns[turn].live)["indent"]),
                "\n" + " " * 3,
            )
        ),
    )
    emit("format", lambda p: p["report"].update(extra="forbidden"))
    emit("process", lambda p: p["calls"].pop())
    emit(
        "wrong_family",
        lambda p: p["calls"][1].update(
            path="policy.py" if episode.turns[turn].path == "core.py" else "core.py"
        ),
    )
    emit(
        "semantic",
        lambda p: p["calls"][1].update(
            code=f"def {episode.turns[turn].function}(x):\n    return 987654321\n"
        ),
    )
    emit(
        "hidden_only",
        lambda p: p["calls"][1].update(
            code=f"def {episode.turns[turn].function}(x):\n"
            + " " * int(dict(episode.turns[turn].live)["indent"])
            + f"return {episode.turns[turn].public_expected!r}\n"
        ),
    )
    result["breakage"] = "{"
    for key, value in episode.turns[turn].retired:
        if key == "indent":
            emit(
                "relapse:style",
                lambda p, value=value: p["calls"][1].update(
                    code=p["calls"][1]["code"].replace(
                        "\n" + " " * int(dict(episode.turns[turn].live)["indent"]),
                        "\n" + " " * int(value),
                    )
                ),
            )
        elif key == "format":
            emit(
                "relapse:format",
                lambda p: p["report"].update(task=episode.turns[turn].task),
            )
        elif key == "delivery":
            emit(
                "relapse:process",
                lambda p, value=value: p["report"].update(delivery=value),
            )
    return result


def dry_run(directory, episode=None, encode=byte_encode):
    """One full DEV replay, no hidden feedback. Inject pinned tokenizer for costs."""
    episode = episode or generate_episode()
    if episode.family != "dev":
        raise ValueError("dry run is DEV only")
    directory = Path(directory)
    workspace = directory / "workspace"
    materialize(episode, workspace)
    executor = Executor(
        workspace, json.loads((workspace / "public_tests.json").read_text())
    )
    journal_path = directory / "loop.jsonl"
    if journal_path.exists():
        raise ValueError("fresh journal required")
    session = Session(
        Register(defaults=episode.defaults, task_handles={"A", "B"}),
        Request("", "tool_call"),
        Journal(journal_path),
    )
    accounting, checks, render_hashes = [], [], []
    feedback = None
    for i, t in enumerate(episode.turns):
        session.request = Request(
            t.request,
            "tool_call",
            t.task,
            encode=encode,
            template_id=episode.template_id,
        )
        messages = []
        if feedback:
            messages.append(
                Message(
                    f"tool{i}",
                    "tool",
                    compact(feedback["results"]),
                    tool_results=tuple(feedback["results"]),
                    executed_tool_calls=tuple(feedback["executed"]),
                    artifact_hashes=tuple(executor.hashes().items()),
                )
            )
        messages.append(Message(f"m{i}", "user", t.request, t.events, adopted=True))
        scripted = reference(episode, i)

        def decoder(rendered, scripted=scripted, t=t, i=i):
            assert len(encode(scripted)) <= 512, (
                "scripted output exceeds fixed generation cap"
            )
            assert {v.entry.key: v.entry.value for v in rendered.live} == dict(t.live)
            assert len(rendered.history_messages) == 2 * i
            render_hashes.append(hashlib.sha256(rendered.text.encode()).hexdigest())
            return DecodeResult(
                scripted,
                output_ids=encode(scripted),
                truncated=False,
                attempted_tool_calls=tuple(json.loads(scripted)["calls"]),
            )

        output, _ = generate_once(session, messages, decoder, tools=TOOL_SCHEMA)
        assert output.encode() == scripted.encode()
        feedback = executor.run(output)
        outcome = check(episode, i, output, executor)
        assert outcome["success"], outcome
        checks.append(
            dict(
                turn=i,
                outcome=outcome,
                executed=feedback,
                artifact_hashes=executor.hashes(),
            )
        )
        row = json.loads(journal_path.read_text().splitlines()[-1])
        assert row["output"] == output and row["failures"] == []
        assert row["after_live_mask"] == list(session.register.live_mask)
        assert row["source_events"] == json.loads(
            compact([asdict(e) for e in t.events])
        )
        assert row["input_token_count"] == len(row["rendered_token_ids"])
        assert (
            hashlib.sha256(row["rendered_messages"].encode()).hexdigest()
            == render_hashes[-1]
        )
        accounting.append(
            dict(
                round=i,
                prompt=row["input_token_count"],
                rendered=len(encode(row["rendered_messages"])),
                generated=len(encode(output)),
            )
        )
        # Same-run sidecar includes final tool results without another generation.
        with (directory / "checker.jsonl").open("a") as stream:
            stream.write(compact(checks[-1]) + "\n")
    result = dict(
        episode_id=episode.episode_id,
        tokenizer="utf8-byte-stub" if encode is byte_encode else "injected",
        accounting=accounting,
        rendered_sha256=render_hashes,
        events_sha256=digest([asdict(e) for e in session.register.events]),
        final_hashes=executor.hashes(),
        checks=checks,
        own_body_counts=dict(
            total=len(accounting),
            first_ten_100_300=sum(
                100 <= r["generated"] <= 300 for r in accounting[:10]
            ),
        ),
        model_cost_projection=None,
    )
    (directory / "accounting.json").write_text(compact(result) + "\n")
    return result


def paired_clauses(rendered, baseline):
    """CPU scoring clauses only; eligibility/cost/provenance gates stay external.

    Inputs are 64 paired episodes of saved check() records, including explicit
    unexecuted records. No outcome-dependent dropping or absolute success floor.
    Episode final success is final integration plus final live-rule compliance;
    any earlier breakage or relapse remains counted in its separate paired gate.
    """
    from math import comb

    if len(rendered) != 64 or len(baseline) != 64:
        raise ValueError("64 episode pairs required")
    wins = losses = broken_r = broken_n = 0
    complete = True
    common = {kind: dict(denominator=0, r=0, n=0, missing=0) for kind in KINDS}
    for r_episode, n_episode in zip(rendered, baseline, strict=True):
        if len(r_episode) != len(n_episode) or len(r_episode) not in (16, 32):
            raise ValueError("unaligned scheduled rounds")
        r_ok = bool(r_episode[-1].get("success", False))
        n_ok = bool(n_episode[-1].get("success", False))
        wins += int(r_ok and not n_ok)
        losses += int(n_ok and not r_ok)
        broken_r += int(
            any(t.get("violations") and t["violations"]["breakage"] for t in r_episode)
        )
        broken_n += int(
            any(t.get("violations") and t["violations"]["breakage"] for t in n_episode)
        )
        for r, n in zip(r_episode, n_episode, strict=True):
            if r["denominators"] != n["denominators"]:
                raise ValueError("gold opportunity mismatch")
            observed = r["observed"] and n["observed"]
            complete &= observed
            for kind in KINDS:
                if not r["denominators"][kind]:
                    continue
                if not observed:
                    common[kind]["missing"] += 1
                    continue
                common[kind]["denominator"] += 1
                common[kind]["r"] += int(r["relapse"][kind])
                common[kind]["n"] += int(n["relapse"][kind])
    discordant = wins + losses
    p = sum(comb(discordant, j) for j in range(wins, discordant + 1)) / 2**discordant
    primary = p <= 0.05 and wins - losses >= 8
    breakage = broken_r - broken_n <= 1
    relapse = all(v["r"] <= v["n"] for v in common.values())
    return dict(
        complete=complete,
        wins=wins,
        losses=losses,
        primary_p=p,
        gain=wins - losses,
        breakage_excess=broken_r - broken_n,
        common_opportunities=common,
        primary_clause=primary,
        breakage_clause=breakage,
        relapse_clause=relapse,
        clauses_pass=bool(complete and primary and breakage and relapse),
    )
