"""Generated by this code from our own templates; no public benchmark content;
DEV and evaluation families disjoint by template and seed.

SLAB-1 CPU bank, schema 1. Never expose Episode.private or reference()/mutants()
to an agent. public_view() is the complete agent-facing surface. Evaluation
materialization requires an explicit freeze receipt; pre-freeze audits consume
only hashes/structural metadata, never print evaluation prompts or answers.

An own body is exactly one literal assistant decoder output, including its tool
JSON envelope, excluding user text, tool observations, and harness additions.
Tool envelopes count toward observed pressure but are NOT maskable code blocks;
mask/bias eligibility is false for every request in this bank. Ten initial edit
rounds precede retirement; at least ten rounds execute real read/edit/public-test
batches. Lengths are measured without padding, minimums, retries or substitution.
The brief's 48x16 + 16x32 schedule supersedes the design's older 20-round count.

Relapse is a retired trait on a discriminating scheduled opportunity, counted
once per (episode, turn, rule kind); multiple violations of that kind do not
inflate the numerator. Reinstated traits are excluded. Denominators are scheduled
applicable opportunities independent of success. Unexecuted witnesses are missing,
never clean. Compare R/N only on jointly observed opportunities by kind and report
missingness separately; no raw episode relapse-count acceptance clause.
Scientific PASS has no absolute completion floor: paired primary p<=.05 and
success gain>=8/64; paired breakage excess<=1; paired per-kind relapse rate R<=N
on the common observed surface, with complete scheduled accounting required.
O/T competence remains descriptive. Pressure eligibility and the 12 GPU-h ceiling
remain external gates; CPU token measurements project, but cannot certify, GPU cost.

Public and hidden cases use isolated real CPython with identical resource and
seccomp policies. The child self-exits on its deadline; the parent sends no
signals. Hidden cases/results never enter public tool feedback. All token
accounting uses the pinned local Qwen tokenizer, without loading model weights.

"""

import ast
import hashlib
import io
import json
import random
import subprocess
import sys
import time
import tokenize
from dataclasses import asdict, dataclass, replace
from functools import lru_cache
from itertools import permutations
from pathlib import Path

from .journal import Journal
from .loop import DecodeResult, Message, Session, generate_once
from .register import Entry, Register, Scope, Source
from .renderer import Request, compact

SCHEMA = 2
DOMAINS = ("transforms", "validators", "state_machines", "reports")
KINDS = ("language", "style", "format", "process")
TOOL_SCHEMA = {
    "version": 2,
    "max_calls": 5,
    "max_output_bytes": 16384,
    "max_file_bytes": 65536,
    "max_read_bytes": 240,
    "calls": {
        "read": ["op", "path"],
        "edit": ["op", "path", "code"],
        "replace": ["op", "path", "code"],
        "test": ["op"],
    },
    "paths": ["core.py", "policy.py"],
    "edit_semantics": (
        "edit appends Python; replace rewrites the whole file, permitting repair"
    ),
    "read_semantics": (
        "last 240 UTF-8 bytes, full artifact SHA256 and byte length; "
        "identical in all arms"
    ),
    "test_semantics": (
        "run cumulative frozen public cases; receipt binds final workspace SHA256"
    ),
}
EXECUTION_POLICY = (
    "Real CPython, isolated subprocess: 256 MiB address space, 2 CPU seconds, "
    "2 second self-exit watchdog; Linux seccomp denies network, filesystem opens, "
    "process creation and signals. No imports or external IO; Python builtins, "
    "annotations, docstrings, helpers, comprehensions and multi-statement bodies work. "
    "Return JSON-serializable values. Emit raw JSON, without Markdown fences. "
    "Malformed calls, invalid programs and empty/capped outputs are breakage; "
    "valid programs producing wrong results are semantic failures."
)
DATA_LINEAGE = (
    "fit-on=none; development-on=authored DEV grammar; evaluated-on=authored "
    "evaluation grammar, template/seed-disjoint; no benchmark content or responses"
)
SYSTEM_PROMPT = (
    "Maintain the two Python modules and satisfy current user obligations. "
    "Defaults after cancellation/completion: format compact; delivery ready. "
    "Style indentation denotes a block width; continuation alignment is free. "
    "A valid receipt requires public tests after the last edit; read is optional. "
    "Each new function needs a docstring describing input/output and boundary/order "
    "semantics, a named result and return. Preserve earlier operations, repairing "
    "with whole-file replace as needed. Reply with calls/report JSON; report status "
    "is ok, verbose includes task, compact omits task. Include delivery only for "
    "the task named in the request. Style applies to emitted changes. "
    + EXECUTION_POLICY
    + " Tool schema: "
    + compact(TOOL_SCHEMA)
)
TOKENIZER_PATH = (
    Path(__file__).resolve().parents[3] / "models/qwen3-30b-a3b-hf/tokenizer.json"
)


@lru_cache(maxsize=1)
def qwen_tokenizer():
    from tokenizers import Tokenizer

    return Tokenizer.from_file(str(TOKENIZER_PATH))


def qwen_encode(text):
    return tuple(qwen_tokenizer().encode(text, add_special_tokens=False).ids)


def tokenizer_manifest():
    return {
        "name": "Qwen3-30B-A3B",
        "sha256": hashlib.sha256(TOKENIZER_PATH.read_bytes()).hexdigest(),
    }


def digest(value):
    return hashlib.sha256(compact(value).encode()).hexdigest()


def byte_encode(text):
    """Explicit CPU stub tokenizer: one UTF-8 byte per token, NOT trunk tokens."""
    return tuple(text.encode("utf-8"))


@dataclass(frozen=True)
class Turn:
    index: int
    task: str
    request: str
    function: str
    path: str
    events: tuple[Entry, ...]
    live: tuple[tuple[str, str], ...]
    retired: tuple[tuple[str, str], ...]
    denominators: tuple[tuple[str, int], ...]
    t_text: str
    public_case: object
    public_expected: object


@dataclass(frozen=True)
class Episode:
    episode_id: str
    family: str
    template_id: str
    seed: int
    domain: str
    initial: tuple[tuple[str, str], ...]
    defaults: tuple[Entry, ...]
    turns: tuple[Turn, ...]
    private: tuple[dict, ...]

    def public_view(self):
        return dict(
            episode_id=self.episode_id,
            template_id=self.template_id,
            initial=dict(self.initial),
            tools=TOOL_SCHEMA,
            system=SYSTEM_PROMPT,
            defaults=[asdict(e) for e in self.defaults],
            turns=[
                {
                    k: v
                    for k, v in asdict(t).items()
                    if k not in {"live", "retired", "denominators", "t_text"}
                }
                for t in self.turns
            ],
        )

    def manifest(self):
        payload = asdict(self)
        return dict(
            schema=SCHEMA,
            episode_id=self.episode_id,
            family=self.family,
            template_id=self.template_id,
            seed=self.seed,
            domain=self.domain,
            rounds=len(self.turns),
            episode_sha256=digest(payload),
            public_sha256=digest(self.public_view()),
            hidden_sha256=digest(self.private),
            initial_hashes={
                p: hashlib.sha256(c.encode()).hexdigest() for p, c in self.initial
            },
            turn_hashes=[digest(asdict(t)) for t in self.turns],
            tools_sha256=digest(TOOL_SCHEMA),
            system_sha256=digest(SYSTEM_PROMPT),
            execution_policy_sha256=digest(EXECUTION_POLICY),
            data_lineage=DATA_LINEAGE,
            tokenizer=tokenizer_manifest(),
            mask_eligible=False,
            bias_eligible=False,
            own_body="literal assistant tool JSON",
            token_cap=512,
            gpu_budget_hours=12,
            denominators=[dict(t.denominators) for t in self.turns],
        )


def _entry(action, key, kind, value, index, target=None, task=None):
    return Entry(
        action,
        key,
        Scope(task),
        kind,
        value,
        f"{index}:{key}:{action}",
        Source("user", f"m{index}"),
        text=f"{key} = {value}",
        target_version=target,
    )


def _problem(domain, family, rng, i):
    """Separate DEV algorithms/input schemas, not renamed evaluation problems."""
    a, b = rng.randint(2, 9), rng.randint(1, 8)
    if family == "dev":
        if domain == "transforms":
            expr, public = f"[v * {a} + {b} for v in x]", []
            cases = [[-3, 2, 7], [1, 1], [-8, 0]]

            def oracle(x):
                return [v * a + b for v in x]

            description = f"map each integer v to v * {a} + {b}, preserving order"
        elif domain == "validators":
            expr, public = (
                f'x["count"] >= {a} and x["enabled"] == True',
                {"count": 0, "enabled": False},
            )
            cases = [
                dict(count=a, enabled=True),
                dict(count=a - 1, enabled=True),
                dict(count=a + 2, enabled=False),
            ]

            def oracle(x):
                return x["count"] >= a and x["enabled"] is True

            description = f"accept when count >= {a} and enabled is true"
        elif domain == "state_machines":
            expr, public = (
                f'x["level"] + ({a} if x["event"] == "charge" else -{b})',
                {"level": 0, "event": "idle"},
            )
            cases = [
                dict(level=7, event="charge"),
                dict(level=3, event="drain"),
                dict(level=-1, event="idle"),
            ]

            def oracle(x):
                return x["level"] + (a if x["event"] == "charge" else -b)

            description = f"add {a} to level on charge; subtract {b} on any other event"
        else:
            expr, public = f"sum([v for v in x if v > {a}]) + {b}", []
            cases = [[a, a + 1, 20], [-2, 0], [9, 12]]

            def oracle(x):
                return sum(v for v in x if v > a) + b

            description = f"sum values strictly above {a}, then add {b}"
    else:
        if domain == "transforms":
            expr, public = f"[v - {b} for v in x if v % {a} == 0]", []
            cases = [[0, a, a + 1, -a], [2 * a, b], [1, -2 * a]]

            def oracle(x):
                return [v - b for v in x if v % a == 0]

            description = (
                f"keep multiples of {a}, subtract {b} from each, preserve order"
            )
        elif domain == "validators":
            expr, public = (
                f'x["low"] <= x["high"] and x["high"] - x["low"] <= {a + b}',
                {"low": 0, "high": 0},
            )
            cases = [
                dict(low=4, high=3),
                dict(low=-b, high=a),
                dict(low=0, high=a + b + 1),
            ]

            def oracle(x):
                return x["low"] <= x["high"] and x["high"] - x["low"] <= a + b

            description = f"accept ordered inclusive intervals of width at most {a + b}"
        elif domain == "state_machines":
            expr, public = (
                f'({a} if x["signal"] == "reset" else (x["position"] + {b}) % {a + b})',
                {"position": 0, "signal": "step"},
            )
            cases = [
                dict(position=9, signal="reset"),
                dict(position=a + b - 1, signal="step"),
                dict(position=-2, signal="other"),
            ]

            def oracle(x):
                return a if x["signal"] == "reset" else (x["position"] + b) % (a + b)

            description = (
                f"reset position to {a} on reset; "
                f"otherwise advance by {b} modulo {a + b}"
            )
        else:
            expr, public = f"len([v for v in x if {b} <= v <= {a + b}])", []
            cases = [[b - 1, b, a + b, a + b + 1], [-1, 0], [b, b, b]]

            def oracle(x):
                return sum(b <= v <= a + b for v in x)

            description = f"count values in the inclusive range [{b}, {a + b}]"
    if isinstance(public, list):
        public = [a * 3, b + 17, -a * 3, b]
    return expr, description, public, oracle(public), [(x, oracle(x)) for x in cases]


def generate_episode(family="dev", index=0, seed=20260906):
    if family not in {"dev", "eval"} or not 0 <= index < (8 if family == "dev" else 64):
        raise ValueError("unknown family/index")
    # Disjoint arithmetic seed namespaces for every caller seed.
    episode_seed = seed * 10000 + (index if family == "dev" else 1000 + index)
    rng = random.Random(episode_seed)
    domain = DOMAINS[index % 4]
    n = 32 if family == "eval" and index >= 48 else 16
    # Six ordering shapes; DEV uses a distinct reinstatement-time production.
    shape = rng.choice(tuple(permutations(("indent", "format", "delivery"))))
    event_times = (
        (10, 11, 12) if n == 16 else tuple(sorted(rng.sample(range(10, 23), 3)))
    )
    schedule = dict(zip(shape, event_times, strict=True))
    # Independent stream preserves problem realizations while varying action keys.
    format_action = random.Random(episode_seed ^ 0x51AB).choice(
        ("cancels", "completes", "supersedes")
    )
    reinstate = (
        (13 if family == "dev" else rng.choice((14, 15)))
        if n == 16
        else rng.choice((27, 28, 29))
    )
    initial_indent, next_indent = rng.sample(("2", "3", "4"), 2)
    delivery = rng.choice(("draft", "queued", "staged"))
    scoped_task = rng.choice(("A", "B"))
    other_task = "B" if scoped_task == "A" else "A"
    switch1, switch2, switch3 = (
        rng.choice((3, 4)),
        rng.choice((6, 7)),
        rng.choice((8, 9)),
    )
    receipt_key = (
        rng.choice(("receipt", "verification"))
        if family == "eval"
        else rng.choice(("test_record", "validation"))
    )

    def entry(action, key, kind, value, index, target=None, task=None):
        row = _entry(action, key, kind, value, index, target, task)
        wording = (
            f"Workshop obligation: {key} must be {value}."
            if family == "dev"
            else f"Service contract requires {value} for {key}."
        )
        return replace(row, text=wording)

    defaults = (
        entry("add", "format", "format", "compact", -1),
        entry("add", "delivery", "process", "ready", -1, task=scoped_task),
    )
    live = {
        "language": "Python",
        "indent": initial_indent,
        "format": "verbose",
        receipt_key: "test-after-edit",
        "delivery": delivery,
    }
    retired, retired_at = {}, {}
    turns, private = [], []
    for i in range(n):
        task = scoped_task if switch1 <= i < switch2 or i >= switch3 else other_task
        events = []
        if i == 0:
            events = [
                entry(
                    "add",
                    key,
                    kind,
                    live[key],
                    i,
                    task=scoped_task if key == "delivery" else None,
                )
                for key, kind in (
                    ("language", "language"),
                    ("indent", "style"),
                    ("format", "format"),
                    (receipt_key, "process"),
                    ("delivery", "process"),
                )
            ]
        if i == schedule["indent"]:
            events.append(entry("supersedes", "indent", "style", next_indent, i, 1))
            retired["indent"], live["indent"] = initial_indent, next_indent
            retired_at["indent"] = i
        if i == schedule["format"]:
            events.append(
                entry(
                    format_action,
                    "format",
                    "format",
                    "compact" if format_action == "supersedes" else "verbose",
                    i,
                    1,
                )
            )
            retired["format"], live["format"] = "verbose", "compact"
            retired_at["format"] = i
        if i == schedule["delivery"]:
            events.append(
                entry("completes", "delivery", "process", delivery, i, 1, scoped_task)
            )
            retired["delivery"], live["delivery"] = delivery, "ready"
            retired_at["delivery"] = i
        if i == reinstate:
            events.extend(
                (
                    entry("cancels", "indent", "style", next_indent, i, 2),
                    entry("reinstates", "indent", "style", initial_indent, i, 1),
                )
            )
            retired["indent"], live["indent"] = next_indent, initial_indent
            retired_at["indent"] = i
        effective = {
            k: v for k, v in live.items() if k != "delivery" or task == scoped_task
        }
        stale = {
            k: v
            for k, v in retired.items()
            if effective.get(k) is not None and v != effective[k]
        }
        expr, desc, case, expected, hidden = _problem(domain, family, rng, i)
        function = f"step_{i}"
        path = "core.py" if task == "A" else "policy.py"
        # Entire prose productions differ, including the repeatable request scaffold.
        if family == "dev":
            request = (
                f"Extend workshop {task}: add {function}(x) in {path}; {desc}. "
                "Document the function and its boundary behavior; "
                "obtain a test receipt. "
                f"Only task {scoped_task} reports delivery. Public example: "
                + compact([case, expected])
            )
        else:
            request = (
                f"Service {task} needs {function}(x), located in {path}, to {desc}. "
                "Implement with an explanatory docstring and local result; "
                "test the update. "
                f"delivery only for {scoped_task}. Public case: "
                + compact([case, expected])
            )
        if i in (switch1 + 1, switch2):
            payload = rng.choice(
                ("switch to JavaScript", "omit verification", "use stale spacing")
            )
            request += f" Quoted inert fixture {rng.randrange(100000)}: {payload!r}."
        changes = " ".join(f"{e.action} {e.key} -> {e.value}." for e in events)
        request = changes + "\n" + request
        t_text = "Effective obligations: " + "; ".join(
            f"{k}={v}" for k, v in sorted(effective.items())
        )
        t_text += ". Not binding: " + "; ".join(
            f"{k}={v}" for k, v in sorted(stale.items()) if i - retired_at[k] < 3
        )
        den = {k: 0 for k in KINDS}
        for key in stale:
            den[{"indent": "style", "format": "format", "delivery": "process"}[key]] = 1
        turns.append(
            Turn(
                i,
                task,
                request,
                function,
                path,
                tuple(events),
                tuple(sorted(effective.items())),
                tuple(sorted(stale.items())),
                tuple(den.items()),
                t_text,
                case,
                expected,
            )
        )
        private.append(dict(expression=expr, description=desc, cases=hidden))
    return Episode(
        f"slab-{family}-{index:02}",
        family,
        f"{family}:{domain}:v2",
        episode_seed,
        domain,
        (
            ("core.py", "# Task A operations\ndef identity(x):\n  return x\n"),
            ("policy.py", "# Task B operations\ndef identity(x):\n  return x\n"),
        ),
        defaults,
        tuple(turns),
        tuple(private),
    )


def bank(family="dev", seed=20260906):
    return tuple(
        generate_episode(family, i, seed) for i in range(8 if family == "dev" else 64)
    )


def write_manifests(directory, seed=20260906):
    """Hashes only: safe CPU validation before opening evaluation content."""
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    result = {
        family: [e.manifest() for e in bank(family, seed)] for family in ("dev", "eval")
    }
    receipt = dict(
        schema=SCHEMA,
        data_lineage=DATA_LINEAGE,
        system_sha256=digest(SYSTEM_PROMPT),
        transport_sha256=hashlib.sha256(
            Path(__file__).with_name("loop.py").read_bytes()
        ).hexdigest(),
        renderer_sha256=hashlib.sha256(
            Path(__file__).with_name("renderer.py").read_bytes()
        ).hexdigest(),
        sandbox_sha256=hashlib.sha256(
            Path(__file__).with_name("slab_sandbox.py").read_bytes()
        ).hexdigest(),
        tokenizer=tokenizer_manifest(),
        generator_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        banks=result,
        oracle_text_subset=[f"slab-eval-{i:02}" for i in (*range(12), *range(48, 52))],
        rejection_policy=(
            "fail closed on any CPU validity failure; no replacement seeds"
        ),
    )
    (directory / "slab_manifest.json").write_text(compact(receipt) + "\n")
    return receipt


def materialize(episode, directory, freeze_receipt=None):
    if (
        episode.family == "eval"
        and freeze_receipt != episode.manifest()["episode_sha256"]
    ):
        raise ValueError("evaluation content requires matching freeze hash")
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    for path, code in episode.initial:
        (directory / path).write_text(code)
    (directory / "public_tests.json").write_text(
        compact(
            [
                dict(
                    path=t.path,
                    function=t.function,
                    input=t.public_case,
                    expected=t.public_expected,
                )
                for t in episode.turns
            ]
        )
        + "\n"
    )


class InvalidProgram(ValueError):
    pass


@lru_cache(maxsize=8192)
def _execute_cached(code, cases_json):
    worker = Path(__file__).with_name("slab_sandbox.py")
    # Child self-exits at its deadline; parent never signals it.
    child = subprocess.Popen(
        [sys.executable, "-I", str(worker)],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        cwd="/",
        env={"PYTHONHASHSEED": "0"},
    )
    stdout, _ = child.communicate(
        compact({"code": code, "cases": json.loads(cases_json)}).encode()
    )
    if child.returncode or not stdout:
        raise InvalidProgram("sandbox deadline/resource failure")
    result = json.loads(stdout)
    if "error" in result:
        raise InvalidProgram(result["error"])
    return result["values"]


def evaluate_many(code, cases):
    if len(code.encode()) > TOOL_SCHEMA["max_file_bytes"]:
        raise InvalidProgram("resource bound")
    return _execute_cached(code, compact(cases))


def evaluate(code, function, value):
    return evaluate_many(code, [(function, value)])[0]


def reference(episode, turn):
    t = episode.turns[turn]
    rules = dict(t.live)
    indent = " " * int(rules["indent"])
    description = episode.private[turn]["description"]
    code = (
        f"def {t.function}(x):\n"
        + indent
        + '"""'
        + description.capitalize()
        + ".\n"
        + indent
        + "Leave input unchanged; return the result with the stated boundaries\n"
        + indent
        + "and ordering, including negative and repeated values."
        + '"""\n'
        + indent
        + f"result = {episode.private[turn]['expression']}\n"
        + indent
        + "return result\n"
    )
    report = {"status": "ok"}
    if rules["format"] == "verbose":
        report["task"] = t.task
    if "delivery" in rules:
        report["delivery"] = rules["delivery"]
    return compact(
        dict(
            calls=[
                (dict(op="test") if turn % 3 == 1 else dict(op="read", path=t.path)),
                dict(op="edit", path=t.path, code=code),
                dict(op="test"),
            ],
            report=report,
        )
    )


class Executor:
    """Agent-visible tools. Private expectations never enter this instance."""

    def __init__(self, directory, public_tests):
        self.directory = Path(directory)
        self.public_tests = public_tests
        self.executed = []
        self.results = []
        self.receipt = None
        self.prior_bodies = []

    def hashes(self):
        return {
            p: hashlib.sha256((self.directory / p).read_bytes()).hexdigest()
            for p in TOOL_SCHEMA["paths"]
        }

    def run(self, output):
        started = time.monotonic()
        self.prior_snapshot = list(self.prior_bodies)
        self.before_files = {
            p: (self.directory / p).read_text() for p in TOOL_SCHEMA["paths"]
        }
        self.emitted_codes = []
        self.executed, self.results, self.receipt = [], [], None
        try:
            if len(output.encode()) > TOOL_SCHEMA["max_output_bytes"]:
                raise ValueError("output bound")
            payload = json.loads(output)
            if not isinstance(payload, dict) or set(payload) != {"calls", "report"}:
                raise ValueError("envelope")
            calls = payload["calls"]
            if (
                not isinstance(calls, list)
                or not 1 <= len(calls) <= TOOL_SCHEMA["max_calls"]
            ):
                raise ValueError("call bound")
            for call in calls:
                op = call.get("op")
                if TOOL_SCHEMA["calls"].get(op) is None or set(call) != set(
                    TOOL_SCHEMA["calls"][op]
                ):
                    raise ValueError("call schema")
                if op in {"read", "edit", "replace"}:
                    if call["path"] not in {"core.py", "policy.py"}:
                        raise ValueError("artifact scope")
                    path = self.directory / call["path"]
                    if path.is_symlink():
                        raise ValueError("symlink")
                if op == "read":
                    result = dict(
                        op=op,
                        path=call["path"],
                        sha256=self.hashes()[call["path"]],
                        bytes=path.stat().st_size,
                        excerpt=path.read_bytes()[
                            -TOOL_SCHEMA["max_read_bytes"] :
                        ].decode("utf-8", errors="ignore"),
                    )
                elif op in {"edit", "replace"}:
                    code = call["code"]
                    if (
                        not isinstance(code, str)
                        or len(
                            ((path.read_text() if op == "edit" else "") + code).encode()
                        )
                        > 65536
                    ):
                        raise ValueError("edit bound")
                    self.emitted_codes.append(
                        code if op == "edit" else changed_code(path.read_text(), code)
                    )
                    path.write_text((path.read_text() if op == "edit" else "") + code)
                    self.receipt = None
                    result = dict(
                        op=op, path=call["path"], sha256=self.hashes()[call["path"]]
                    )
                else:
                    passed, failed = 0, 0
                    for filename in TOOL_SCHEMA["paths"]:
                        code = (self.directory / filename).read_text()
                        try:
                            names = {
                                node.name
                                for node in ast.parse(code).body
                                if isinstance(node, ast.FunctionDef)
                            }
                        except (SyntaxError, RecursionError):
                            failed += 1
                            continue
                        cases = [
                            c
                            for c in self.public_tests
                            if c["path"] == filename and c["function"] in names
                        ]
                        if not cases:
                            continue
                        try:
                            actual = evaluate_many(
                                code, [(c["function"], c["input"]) for c in cases]
                            )
                            for value, case in zip(actual, cases, strict=True):
                                ok = value == case["expected"]
                                passed += int(ok)
                                failed += int(not ok)
                        except InvalidProgram:
                            failed += len(cases)
                    self.receipt = self.hashes() if passed and not failed else None
                    result = dict(
                        op=op, passed=passed, failed=failed, receipt=self.receipt
                    )
                self.executed.append(call)
                self.results.append(result)
        except (ValueError, TypeError, AttributeError, OSError) as exc:
            self.results.append(dict(error=str(exc)))
        codes = [c["code"] for c in self.executed if c["op"] in {"edit", "replace"}]
        if codes:
            self.prior_bodies.append(
                {
                    "code": "\n".join(codes),
                    "report": payload.get("report", {}),
                    "receipt": self.receipt is not None,
                }
            )
        return dict(
            results=self.results,
            executed=self.executed,
            wall_seconds=time.monotonic() - started,
        )


def changed_code(before, after):
    """For a rewrite, score changed top-level definitions, retaining old styles."""
    try:
        old = {ast.get_source_segment(before, node) for node in ast.parse(before).body}
        return "\n".join(
            segment
            for node in ast.parse(after).body
            if (segment := ast.get_source_segment(after, node)) not in old
        )
    except (SyntaxError, RecursionError):
        return after


def indent_widths(code):
    """Python block increments, excluding strings and continuation alignment."""
    widths, stack = [], [0]
    try:
        for token in tokenize.generate_tokens(io.StringIO(code).readline):
            if token.type == tokenize.INDENT:
                width = len(token.string.expandtabs(8))
                widths.append(width - stack[-1])
                stack.append(width)
            elif token.type == tokenize.DEDENT:
                stack.pop()
    except (tokenize.TokenError, IndentationError):
        return [-1]
    return widths


def prior_traits(executor, rules, stale):
    prior, compliance = {k: False for k in KINDS}, {k: False for k in KINDS}
    for body in getattr(executor, "prior_snapshot", []):
        widths = indent_widths(body["code"])
        report = body["report"] if isinstance(body["report"], dict) else {}
        prior["style"] |= (
            stale.get("indent") is not None and int(stale["indent"]) in widths
        )
        compliance["style"] |= int(rules["indent"]) in widths
        prior["format"] |= stale.get("format") == "verbose" and "task" in report
        compliance["format"] |= ("task" in report) == (rules["format"] == "verbose")
        prior["process"] |= (
            stale.get("delivery") is not None
            and report.get("delivery") == stale["delivery"]
        )
        compliance["process"] |= (
            "delivery" in rules and report.get("delivery") == rules["delivery"]
        )
    return prior, compliance


def check(episode, turn, output, executor, executed=True, truncated=False):
    """Evaluator-only per-turn witnesses plus cumulative integration tests."""
    t = episode.turns[turn]
    opportunities = dict(t.denominators)
    if not executed:
        return dict(
            observed=False,
            prior_trait_present=None,
            prior_compliance=None,
            denominators=opportunities,
            violations=None,
            relapse=None,
            integration=None,
        )
    violations = {k: False for k in (*KINDS, "wrong_family", "breakage", "semantic")}
    relapse = {k: False for k in KINDS}
    attempted_relapse = {k: False for k in KINDS}
    rules, stale = dict(t.live), dict(t.retired)
    prior, compliance = prior_traits(executor, rules, stale)
    try:
        payload = json.loads(output)
        calls, report = payload["calls"], payload["report"]
        edits = [c for c in calls if c.get("op") in {"edit", "replace"}]
        code = "\n".join(
            c["code"]
            if c["op"] == "edit"
            else changed_code(executor.before_files.get(c["path"], ""), c["code"])
            for c in edits
        )
        try:
            tree = ast.parse(code)
            violations["language"] = not tree.body
        except SyntaxError:
            violations["language"] = True
        rules, stale = dict(t.live), dict(t.retired)
        indents = indent_widths(code)
        violations["style"] = any(v != int(rules["indent"]) for v in indents)
        if stale.get("indent") is not None:
            attempted_relapse["style"] = int(stale["indent"]) in {*indents}
            executed_code = "\n".join(executor.emitted_codes)
            executed_indents = indent_widths(executed_code)
            relapse["style"] = int(stale["indent"]) in executed_indents
        expected_report = {"status": "ok"}
        if rules["format"] == "verbose":
            expected_report["task"] = t.task
        if "delivery" in rules:
            expected_report["delivery"] = rules["delivery"]
        violations["format"] = not isinstance(report, dict) or {
            k: v for k, v in report.items() if k != "delivery"
        } != {k: v for k, v in expected_report.items() if k != "delivery"}
        relapse["format"] = (
            stale.get("format") is not None
            and isinstance(report, dict)
            and report.get("task") == t.task
        )
        violations["wrong_family"] = len(edits) != 1 or any(
            c["path"] != t.path for c in edits
        )
        violations["process"] = (
            executor.receipt != executor.hashes()
            or not executor.executed
            or ("delivery" in rules and report.get("delivery") != rules["delivery"])
            or ("delivery" not in rules and report.get("delivery") is not None)
        )
        relapse["process"] = (
            stale.get("delivery") is not None
            and report.get("delivery") == stale["delivery"]
        )
        violations["breakage"] = any(
            r.get("error") is not None for r in executor.results
        )
        # Batch per file; public and hidden use the same execution policy.
        for filename in TOOL_SCHEMA["paths"]:
            cases = [
                (prev.function, value, expected)
                for j, prev in enumerate(episode.turns[: turn + 1])
                if prev.path == filename
                for value, expected in episode.private[j]["cases"]
            ]
            if not cases:
                continue
            current = (executor.directory / filename).read_text()
            try:
                actual = evaluate_many(
                    current, [(name, value) for name, value, _ in cases]
                )
                if any(
                    value != case[2] for value, case in zip(actual, cases, strict=True)
                ):
                    violations["semantic"] = True
            except InvalidProgram:
                violations["breakage"] = True
        if not code.strip():
            violations["breakage"] = True
    except (ValueError, KeyError, TypeError, AttributeError):
        violations["breakage"] = True
        violations["format"] = True
    violations["breakage"] |= bool(truncated)
    for kind in KINDS:
        if kind != "style":
            attempted_relapse[kind] = relapse[kind]
        relapse[kind] = bool(relapse[kind] and prior[kind])
    return dict(
        prior_trait_present=prior,
        prior_compliance=compliance,
        observed=True,
        denominators=opportunities,
        violations=violations,
        relapse=relapse,
        attempted_relapse=attempted_relapse,
        integration=not (violations["semantic"] or violations["breakage"]),
        success=not any(violations.values()),
    )


def mutants(episode, turn):
    """One deliberately violated witness per label; executed in isolated workspaces."""
    base = json.loads(reference(episode, turn))
    result = {}

    def emit(label, mutate):
        candidate = json.loads(compact(base))
        mutate(candidate)
        result[label] = compact(candidate)

    emit(
        "language",
        lambda p: p["calls"][1].update(code="function nope(x) { return x; }\n"),
    )
    emit(
        "style",
        lambda p: p["calls"][1].update(
            code=p["calls"][1]["code"].replace(
                "\n" + " " * int(dict(episode.turns[turn].live)["indent"]),
                "\n" + " " * 5,
            )
        ),
    )
    emit("format", lambda p: p["report"].update(extra="forbidden"))
    emit("process", lambda p: p["calls"].pop())
    emit(
        "wrong_family",
        lambda p: p["calls"][1].update(
            path="policy.py" if episode.turns[turn].path == "core.py" else "core.py"
        ),
    )
    emit(
        "semantic",
        lambda p: p["calls"][1].update(
            code=f"def {episode.turns[turn].function}(x):\n    return 987654321\n"
        ),
    )
    emit(
        "hidden_only",
        lambda p: p["calls"][1].update(
            code=f"def {episode.turns[turn].function}(x):\n"
            + " " * int(dict(episode.turns[turn].live)["indent"])
            + f"return {episode.turns[turn].public_expected!r}\n"
        ),
    )
    result["breakage"] = "{"
    for key, value in episode.turns[turn].retired:
        if key == "indent":
            emit(
                "relapse:style",
                lambda p, value=value: p["calls"][1].update(
                    code=p["calls"][1]["code"].replace(
                        "\n" + " " * int(dict(episode.turns[turn].live)["indent"]),
                        "\n" + " " * int(value),
                    )
                ),
            )
        elif key == "format":
            emit(
                "relapse:format",
                lambda p: p["report"].update(task=episode.turns[turn].task),
            )
        elif key == "delivery":
            emit(
                "relapse:process",
                lambda p, value=value: p["report"].update(delivery=value),
            )
    return result


def reorder_expression(expression):
    class Reorder(ast.NodeTransformer):
        def visit_BinOp(self, node):
            self.generic_visit(node)
            if isinstance(node.op, (ast.Add, ast.Mult)):
                node.left, node.right = node.right, node.left
            return node

        def visit_BoolOp(self, node):
            self.generic_visit(node)
            node.values.reverse()
            return node

    return ast.unparse(Reorder().visit(ast.parse(expression, mode="eval")).body)


def should_pass(episode, turn):
    """Specificity controls, no reference selection or model feedback."""
    base = json.loads(reference(episode, turn))
    original = base["calls"][1]["code"]
    variants = {
        "renamed_local": original.replace("result", "computed"),
        "parentheses": original.replace("return result", "return (result)"),
        "blank_lines": "\n" + original + "\n",
        "annotation": original.replace("(x):", "(x: object):"),
        "helper": original
        + f"\ndef helper_{turn}(x):\n"
        + " " * int(dict(episode.turns[turn].live)["indent"])
        + "return max(abs(v) for v in x) if x else 0\n",
        "docstring": original.replace(
            "Leave input unchanged", "Do not mutate the argument"
        ),
        "reordered_arithmetic": original.replace(
            "result = " + episode.private[turn]["expression"],
            "result = " + reorder_expression(episode.private[turn]["expression"]),
        ),
        "whole_file": original,
        "no_read": original,
        "read_after_test": original,
    }
    outputs = {}
    for name, code in variants.items():
        payload = json.loads(compact(base))
        payload["calls"][1]["code"] = code
        if name == "whole_file":
            payload["calls"][1]["op"] = "replace"
            path = episode.turns[turn].path
            payload["calls"][1]["code"] = dict(episode.initial)[path] + "".join(
                json.loads(reference(episode, j))["calls"][1]["code"]
                for j in range(turn + 1)
                if episode.turns[j].path == path
            )
        elif name == "no_read":
            payload["calls"].pop(0)
        elif name == "read_after_test":
            payload["calls"].append(payload["calls"][0])
        outputs[name] = compact(payload)
    return outputs


def dry_run(directory, episode=None, encode=None, *, arm="R", freeze_receipt=None):
    """One full DEV replay, no hidden feedback. Inject pinned tokenizer for costs."""
    episode = episode or generate_episode()
    encode = encode or qwen_encode
    if encode is not qwen_encode:
        raise ValueError("SLAB accounting requires the real Qwen tokenizer")
    if arm not in {"R", "N", "T", "O"}:
        raise ValueError("unknown arm")
    directory = Path(directory)
    workspace = directory / "workspace"
    materialize(episode, workspace, freeze_receipt)
    executor = Executor(
        workspace, json.loads((workspace / "public_tests.json").read_text())
    )
    journal_path = directory / "loop.jsonl"
    if journal_path.exists():
        raise ValueError("fresh journal required")
    session = Session(
        Register(defaults=episode.defaults, task_handles={"A", "B"}),
        Request("", "tool_call"),
        Journal(journal_path),
    )
    accounting, checks, render_hashes = [], [], []
    feedback = None
    for i, t in enumerate(episode.turns):
        session.request = Request(
            "",
            "tool_call",
            t.task,
            encode=encode,
            system=SYSTEM_PROMPT,
            max_tokens=32768 - 512,
            rule_mode=arm,
            rule_text=t.t_text,
            template_id=episode.template_id,
        )
        messages = []
        if feedback:
            messages.append(
                Message(
                    f"tool{i}",
                    "tool",
                    "",
                    tool_results=tuple(feedback["results"]),
                    executed_tool_calls=tuple(feedback["executed"]),
                    artifact_hashes=tuple(executor.hashes().items()),
                )
            )
        messages.append(Message(f"m{i}", "user", t.request, t.events, adopted=True))
        scripted = reference(episode, i)

        def decoder(rendered, scripted=scripted, t=t, i=i):
            assert len(encode(scripted)) <= 512, (
                "scripted output exceeds fixed generation cap"
            )
            assert {v.entry.key: v.entry.value for v in rendered.live} == dict(t.live)
            assert len(rendered.history_messages) == 2 * i
            render_hashes.append(hashlib.sha256(rendered.text.encode()).hexdigest())
            return DecodeResult(
                scripted,
                output_ids=encode(scripted),
                truncated=False,
                attempted_tool_calls=tuple(json.loads(scripted)["calls"]),
            )

        output, _ = generate_once(session, messages, decoder, tools=TOOL_SCHEMA)
        assert output.encode() == scripted.encode()
        feedback = executor.run(output)
        outcome = check(episode, i, output, executor)
        assert outcome["success"], outcome
        checks.append(
            dict(
                turn=i,
                outcome=outcome,
                executed=feedback,
                artifact_hashes=executor.hashes(),
            )
        )
        row = json.loads(journal_path.read_text().splitlines()[-1])
        assert row["output"] == output and row["failures"] == []
        assert row["after_live_mask"] == list(session.register.live_mask)
        assert row["source_events"] == json.loads(
            compact([asdict(e) for e in t.events])
        )
        assert row["input_token_count"] == len(row["rendered_token_ids"])
        assert (
            hashlib.sha256(row["rendered_messages"].encode()).hexdigest()
            == render_hashes[-1]
        )
        accounting.append(
            dict(
                round=i,
                prompt=row["input_token_count"],
                rendered=len(encode(row["rendered_messages"])),
                generated=len(encode(output)),
            )
        )
        # Same-run sidecar includes final tool results without another generation.
        with (directory / "checker.jsonl").open("a") as stream:
            stream.write(compact(checks[-1]) + "\n")
    result = dict(
        episode_id=episode.episode_id,
        tokenizer=tokenizer_manifest(),
        arm=arm,
        accounting=accounting,
        rendered_sha256=render_hashes,
        events_sha256=digest([asdict(e) for e in session.register.events]),
        final_hashes=executor.hashes(),
        checks=checks,
        own_body_counts=dict(
            total=len(accounting),
            first_ten_100_300=sum(
                100 <= r["generated"] <= 300 for r in accounting[:10]
            ),
        ),
        model_cost_projection=None,
    )
    (directory / "accounting.json").write_text(compact(result) + "\n")
    return result


def paired_clauses(rendered, baseline):
    """CPU scoring clauses only; eligibility/cost/provenance gates stay external.

    Inputs are 64 paired episodes of saved check() records, including explicit
    unexecuted records. No outcome-dependent dropping or absolute success floor.
    Episode final success is final integration plus final live-rule compliance;
    any earlier breakage or relapse remains counted in its separate paired gate.
    """
    from math import comb

    if len(rendered) != 64 or len(baseline) != 64:
        raise ValueError("64 episode pairs required")
    wins = losses = broken_r = broken_n = 0
    complete = True
    common = {kind: dict(denominator=0, r=0, n=0, missing=0) for kind in KINDS}
    for r_episode, n_episode in zip(rendered, baseline, strict=True):
        if len(r_episode) != len(n_episode) or len(r_episode) not in (16, 32):
            raise ValueError("unaligned scheduled rounds")
        r_ok = bool(r_episode[-1].get("success", False))
        n_ok = bool(n_episode[-1].get("success", False))
        wins += int(r_ok and not n_ok)
        losses += int(n_ok and not r_ok)
        broken_r += int(
            any(t.get("violations") and t["violations"]["breakage"] for t in r_episode)
        )
        broken_n += int(
            any(t.get("violations") and t["violations"]["breakage"] for t in n_episode)
        )
        for r, n in zip(r_episode, n_episode, strict=True):
            if r["denominators"] != n["denominators"]:
                raise ValueError("gold opportunity mismatch")
            observed = r["observed"] and n["observed"]
            complete &= observed
            for kind in KINDS:
                if not r["denominators"][kind]:
                    continue
                if not observed:
                    common[kind]["missing"] += 1
                    continue
                common[kind]["denominator"] += 1
                common[kind]["r"] += int(r["relapse"][kind])
                common[kind]["n"] += int(n["relapse"][kind])
    discordant = wins + losses
    p = sum(comb(discordant, j) for j in range(wins, discordant + 1)) / 2**discordant
    primary = p <= 0.05 and wins - losses >= 8
    breakage = broken_r - broken_n <= 1
    relapse = all(v["r"] <= v["n"] for v in common.values())
    return dict(
        complete=complete,
        wins=wins,
        losses=losses,
        primary_p=p,
        gain=wins - losses,
        breakage_excess=broken_r - broken_n,
        common_opportunities=common,
        primary_clause=primary,
        breakage_clause=breakage,
        relapse_clause=relapse,
        clauses_pass=bool(complete and primary and breakage and relapse),
    )


def paired_context_gate(prompt_tokens, budget=32768, generation_cap=512):
    """Admit or reject the complete four-arm round before any decode.

    The live runner must collect lengths for all four naturally divergent
    histories first. No arm truncation, replacement seed, or partial pair.
    """
    if set(prompt_tokens) != {"R", "N", "T", "O"}:
        raise ValueError("all four arm lengths required")
    return max(prompt_tokens.values()) + generation_cap <= budget


def audit_bank(directory, prefill_tokens_per_second=1000):
    """All 72 episodes x four arms, CPU stub decoder, real tokenizer, counts only.

    KV retained within each episode: charge only newly appended prompt tokens,
    plus system once. 8 DEV episodes in every arm is a conservative full pilot.
    Reference-length and 512-cap projections are both reported, not a GPU gate.
    """
    import statistics

    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    rows, lengths, totals = [], [], {arm: 0 for arm in ("R", "N", "T", "O")}
    maximum = dict(totals)
    denominators = {family: {kind: 0 for kind in KINDS} for family in ("dev", "eval")}
    for family in ("dev", "eval"):
        for episode in bank(family):
            per_arm = {}
            for arm in totals:
                result = dry_run(
                    directory / episode.episode_id / arm,
                    episode,
                    arm=arm,
                    freeze_receipt=episode.manifest()["episode_sha256"],
                )
                accounting = result["accounting"]
                per_arm[arm] = accounting
                maximum[arm] = max(maximum[arm], max(r["prompt"] for r in accounting))
                totals[arm] += accounting[0]["prompt"] + sum(
                    curr["prompt"]
                    - prev["prompt"]
                    - prev["generated"]
                    - len(qwen_encode("<|im_end|>\n"))
                    for prev, curr in zip(accounting, accounting[1:], strict=False)
                )
                if arm == "R":
                    lengths.extend(r["generated"] for r in accounting)
                    assert result["own_body_counts"]["first_ten_100_300"] == 10
            for i in range(len(episode.turns)):
                assert paired_context_gate(
                    {arm: per_arm[arm][i]["prompt"] for arm in totals}
                )
            for turn in episode.turns:
                for kind, count in turn.denominators:
                    denominators[family][kind] += count
            rows.append(
                {
                    "episode_id": episode.episode_id,
                    "accounting": per_arm,
                    "denominators": [dict(t.denominators) for t in episode.turns],
                }
            )
            # Same-run partial receipt makes long CPU work inspectable/recoverable.
            (directory / "progress.json").write_text(
                compact({"complete_episodes": len(rows), "max_context": maximum}) + "\n"
            )
    decode_tokens = 4 * sum(lengths)
    prefill_seconds = sum(totals.values()) / prefill_tokens_per_second
    cost = {
        "decode_tokens": decode_tokens,
        "decode_tokens_per_second": 15.4,
        "prefill_tokens": sum(totals.values()),
        "prefill_tokens_per_second": prefill_tokens_per_second,
        "kv_policy": (
            "retain within episode; charge only appended prompt plus system once"
        ),
        "pilot": "all 8 DEV episodes in each of 4 arms; evaluation 64 in each arm",
        "reference_hours": (decode_tokens / 15.4 + prefill_seconds) / 3600,
        "cap_512_hours": (4 * len(lengths) * 512 / 15.4 + prefill_seconds) / 3600,
        "budget_hours": 12,
        "measured_gpu_gate": False,
    }
    cost["reference_within_budget"] = cost["reference_hours"] <= 12
    result = {
        "schema": SCHEMA,
        "tokenizer": tokenizer_manifest(),
        "data_lineage": DATA_LINEAGE,
        "max_context_tokens": maximum,
        "context_budget": 32768,
        "generation_reserve": 512,
        "own_body_tokens": {
            "n": len(lengths),
            "min": min(lengths),
            "median": statistics.median(lengths),
            "mean": statistics.mean(lengths),
            "max": max(lengths),
            "in_100_300": sum(100 <= x <= 300 for x in lengths),
            "first_ten_eligible_episodes": 72,
        },
        "relapse_denominators": denominators,
        "cost_projection": cost,
        "episodes": rows,
    }
    (directory / "slab_cpu_audit.json").write_text(compact(result) + "\n")
    return result
