"""Generate LONG-cohort records THROUGH THE PUBLISHED PACKAGE (transformers path).

Exp 4C draft (results/memorycode-long/REGISTRATION-4C-DRAFT.md): the research runtime
and the package's ``transformers`` bf16 path render identical prompts but take
different greedy paths, so a result attributable to the artifact must be generated by
the artifact. This runner loads the assembled hub build with ``trust_remote_code``,
builds every prompt with the package's own ``FocusSession`` (flag on = ``focus``, flag
off = ``base``), asserts token-count equality between the two arms and with the
research prompt builder, generates greedily, scores with the vendored checker, and
writes records in the research schema so ``memorycode_screen.py summarize --runtime
package`` reads them unchanged.

Writes results/memorycode-long/<split>-<model>-package-role_evicted/item-<id>.json.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

_spec = importlib.util.spec_from_file_location(
    "memorycode_screen", ROOT / "scripts" / "memorycode_screen.py"
)
screen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(screen)


def package_sha256(hub: Path) -> str:
    """One hash over the files that define the artifact: config, remote-code modules,
    tokenizer, the weight index and every weight shard (in name order)."""
    h = hashlib.sha256()
    names = sorted(
        p.name
        for p in hub.iterdir()
        if p.is_file()
        and (
            p.suffix in (".json", ".py", ".txt")
            or p.suffix == ".safetensors"
            or p.name == "merges.txt"
        )
        and p.name != "README.md"
    )
    for name in names:
        h.update(name.encode())
        with (hub / name).open("rb") as f:
            for chunk in iter(lambda: f.read(1 << 24), b""):
                h.update(chunk)
    return h.hexdigest()


def package_manifest(args, root: Path, hub: Path) -> dict:
    manifest = screen.run_manifest(args, root)
    manifest.update(
        {
            "generation_path": "transformers",
            "package_dir": str(hub),
            "package_sha256": package_sha256(hub),
            "tokenizer_sha256": screen._sha256(hub / "tokenizer.json"),
            "weights_sha256": screen._sha256(hub / "model.safetensors.index.json"),
            "window": args.window,
            "budget_tokens": None,
        }
    )
    return manifest


def generate_package(session, request, head, sep, max_new, deadline) -> dict:
    """Greedy generation through ``FocusSession.generate``; a wall-clock overrun is a
    terminal timeout (Exp 4 amendment 2), enforced with ``max_time``."""
    import torch

    started = time.monotonic()
    text = session.generate(
        request,
        head=head,
        separator=sep,
        max_new_tokens=max_new,
        max_time=deadline,
    )
    seconds = time.monotonic() - started
    ids = list(session.last["generated_token_ids"])
    eos = session.model.config.eos_token_id
    eos_ids = set(eos if isinstance(eos, (list, tuple)) else [eos])
    if ids and ids[-1] in eos_ids:
        ids = ids[:-1]
    timed_out = seconds > deadline
    truncated = len(ids) >= max_new
    termination = "timeout" if timed_out else ("cap" if truncated else "eos")
    del torch
    return {
        "text": session.decode(ids),
        "generated_token_ids": ids,
        "prompt_tokens": session.last["prompt_tokens"],
        "n_generated": len(ids),
        "timed_out": timed_out,
        "truncated": truncated,
        "termination": termination,
        "seconds": seconds,
        "text_skip_special": text,
    }


def run(args) -> None:
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    from stencil import memorycode as mc

    hub = Path(args.hub)
    root = screen.OUT_LONG
    args.cohort = "long"
    args.policy = "role_evicted"
    args.window = mc.WINDOW
    args.runtime = "package"
    manifest = package_manifest(args, root, hub)
    manifest["budget_tokens"] = mc.BUDGET
    out_dir = screen._out_dir(args)
    out_dir.mkdir(parents=True, exist_ok=True)
    compute_score = mc.vendored_checker()
    research_tokenizer = screen._tokenizer()
    items = screen.load_items(args.split, root=root)[args.start :]
    if args.limit:
        items = items[: args.limit]
    if args.ids:
        items = [it for it in items if it["id"] in set(args.ids)]
    started = time.monotonic()
    model = None
    tokenizer = None
    for item in items:
        path = out_dir / f"item-{item['id']}.json"
        record = None
        if path.exists() and not args.force:
            record = json.loads(path.read_text())
            if not screen._record_matches(record, manifest):
                raise SystemExit(f"{path}: record made under another configuration")
        missing = [a for a in args.arms if not record or a not in record["arms"]]
        if not missing:
            continue
        if args.ceiling_seconds:
            spent = screen._generation_seconds(out_dir, args.arms)
            if (
                spent >= args.ceiling_seconds
                or screen._ceiling_marker(out_dir).exists()
            ):
                screen._write_atomic(
                    screen._ceiling_marker(out_dir),
                    {
                        "cumulative_generation_seconds": spent,
                        "ceiling_seconds": args.ceiling_seconds,
                        "arms": list(args.arms),
                        "stopped_before_item": item["id"],
                        "utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    },
                )
                print(f"stopping: ceiling {args.ceiling_seconds:.1f} s reached")
                break
        elapsed_min = (time.monotonic() - started) / 60
        needed_min = len(missing) * args.deadline / 60
        if args.budget_minutes and elapsed_min >= args.budget_minutes - needed_min:
            print(f"stopping: {elapsed_min:.1f} min elapsed of {args.budget_minutes}")
            break
        if model is None:
            tokenizer = AutoTokenizer.from_pretrained(hub)
            model = AutoModelForCausalLM.from_pretrained(
                hub, trust_remote_code=True, dtype=torch.bfloat16, device_map="cuda"
            )
            model.eval()
        dialogue = mc.load_dialogue(item["dialogue"])
        query = item["queries"][0]
        head, sep, request = mc.long_request(dialogue, query)
        research_base = mc.build_long_prompt(
            dialogue, item["session"], query, research_tokenizer, ""
        )["prompt_tokens"]
        if record is None:
            record = {
                "id": item["id"],
                "split": item["split"],
                "model": args.model,
                "session": item["session"],
                "queries": item["queries"],
                "history_regex": item["history_regex"],
                "manifest": manifest,
                "arms": {},
            }
        for arm in missing:
            flag = arm == "focus"
            session = model.new_session(tokenizer, stencil_focus=flag)
            for role, text, rendered in mc.focus_session_messages(
                dialogue, item["session"]
            ):
                session.add_message(role, text, rendered=rendered)
            prompt = session.build_prompt(request, head=head, separator=sep)
            built = dict(session.last)
            # Paired equality asserted BEFORE generation: both arms equal the
            # research builder's base prompt token count (amendment 2; parity by
            # construction).
            if built["prompt_tokens"] != research_base:
                raise SystemExit(
                    f"item {item['id']} arm {arm}: package prompt "
                    f"{built['prompt_tokens']} tokens != research base {research_base}"
                )
            gen = generate_package(
                session, request, head, sep, args.max_new, args.deadline
            )
            gen["query"] = query
            gen["prompt_sha256"] = hashlib.sha256(prompt.encode()).hexdigest()
            gen["window"] = {
                k: v
                for k, v in built.items()
                if k not in ("prompt", "thread_text_kept", "generated_token_ids")
            }
            gen["failures"] = mc.output_failures(
                gen["text"],
                gen["generated_token_ids"],
                gen["truncated"],
                gen["timed_out"],
            )
            gen["scores"] = mc.score_generation(
                gen["text"],
                item["history_regex"],
                compute_score,
                required=item["required"][query],
                structure=item["structure"][query],
            )
            if gen["timed_out"]:
                gen["scores"]["strict"] = False
                if gen["scores"].get("fraction_required") is not None:
                    gen["scores"]["fraction_required"] = 0.0
            reminder = built.get("reminder", "")
            record["arms"][arm] = {
                "policy": "role_evicted" if flag else None,
                "selected_sentences": built.get("evicted_sentences", 0),
                "kept_sentences": built.get("kept_sentences", 0),
                "reminder": reminder,
                "reminder_tokens": built.get("reminder_tokens", 0),
                "reminder_empty": not reminder,
                "generations": [gen],
                "strict": gen["scores"]["strict"],
                "fraction": gen["scores"]["fraction"],
            }
            print(
                f"{item['id']} {arm}: strict={gen['scores']['strict']} "
                f"frac_req={gen['scores']['fraction_required']} "
                f"tokens={built.get('reminder_tokens', 0)} end={gen['termination']} "
                f"{gen['seconds']:.1f}s",
                flush=True,
            )
            screen._write_atomic(path, record)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--split", choices=["setup_long", "screen_long"], required=True)
    parser.add_argument("--model", choices=["1.7b", "4b"], default="4b")
    parser.add_argument(
        "--hub", default=str(ROOT / "deploy/stencil_focus/build/hub-4b")
    )
    parser.add_argument("--arms", nargs="+", default=["base", "focus"])
    parser.add_argument("--start", type=int, default=0)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--ids", nargs="+", default=None)
    parser.add_argument("--max-new", type=int, default=screen.MAX_NEW)
    parser.add_argument("--deadline", type=float, default=screen.DEADLINE)
    parser.add_argument("--budget-minutes", type=float, default=0.0)
    parser.add_argument("--ceiling-seconds", type=float, default=0.0)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args(argv)
    run(args)
    return 0


if __name__ == "__main__":
    sys.exit(main())
