"""Generate LONG-cohort records THROUGH THE PUBLISHED PACKAGE (transformers path).

Exp 4C (results/memorycode-long/REGISTRATION-4C.md): the result must be attributable
to the artifact, so every prompt is built by the package's own ``FocusSession`` (flag
on = ``focus``, flag off = ``base``) and every output is generated by the package's
``transformers`` path. The runner asserts token-count equality between the two arms
and with the research prompt builder before generation, records raw generated ids
(EOS included) and scored ids (terminal EOS removed), the prompt text, the package
fingerprint (per-file SHA-256 of the hub build) and the environment (torch /
transformers versions, attention backend), appends every attempt to
``attempts.jsonl`` (interrupted attempts count against the budget), and enforces the
per-slice budget and the cumulative ceiling.

Items come from the frozen manifest (default results/memorycode-long/items-4c.json);
records go to results/memorycode-long/<split>-<model>-package-role_evicted/.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

_spec = importlib.util.spec_from_file_location(
    "memorycode_screen", ROOT / "scripts" / "memorycode_screen.py"
)
screen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(screen)

FINGERPRINT_KEYS = (
    "model",
    "policy",
    "decoding",
    "window",
    "budget_tokens",
    "items_sha256",
    "package_sha256",
    "generation_path",
    "environment",
)


def package_files(hub: Path) -> dict[str, str]:
    """Per-file SHA-256 of everything that defines the artifact (weights, index,
    config, tokenizer files, remote-code modules); README.md excluded."""
    out = {}
    for p in sorted(hub.iterdir()):
        if not p.is_file() or p.name == "README.md":
            continue
        out[p.name] = screen._sha256(p)
    return out


def package_fingerprint(files: dict[str, str]) -> str:
    h = hashlib.sha256()
    for name in sorted(files):
        h.update(f"{name}\n{files[name]}\n".encode())
    return h.hexdigest()


def environment() -> dict:
    import torch
    import transformers

    return {
        "python": sys.version.split()[0],
        "torch": torch.__version__,
        "transformers": transformers.__version__,
        "cuda": torch.version.cuda,
        "attn_implementation": None,  # filled after the model is loaded
    }


def package_manifest(args, root: Path, hub: Path, items_path: Path) -> dict:
    manifest = screen.run_manifest(args, root)
    files = package_files(hub)
    manifest.update(
        {
            "generation_path": "transformers",
            "package_dir": str(hub),
            "package_files": files,
            "package_sha256": package_fingerprint(files),
            "tokenizer_sha256": files.get("tokenizer.json"),
            "weights_sha256": [
                files[n] for n in sorted(files) if n.endswith(".safetensors")
            ],
            "items_file": str(items_path),
            "items_sha256": screen._sha256(items_path),
            "window": args.window,
            "budget_tokens": None,
            "environment": environment(),
        }
    )
    return manifest


def fingerprint_matches(a: dict, b: dict) -> bool:
    """Equality of the registered fingerprint keys; an attention backend that is
    still unknown (None) on one side is not a mismatch."""
    for k in FINGERPRINT_KEYS:
        if k == "environment":
            ea, eb = a.get(k) or {}, b.get(k) or {}
            for kk in set(ea) | set(eb):
                if ea.get(kk) is None or eb.get(kk) is None:
                    continue
                if ea.get(kk) != eb.get(kk):
                    return False
        elif a.get(k) != b.get(k):
            return False
    return True


def record_matches(record: dict, manifest: dict) -> bool:
    return fingerprint_matches(record.get("manifest") or {}, manifest)


def eos_ids(model) -> list[int]:
    eos = model.config.eos_token_id
    ids = set(eos if isinstance(eos, (list, tuple)) else [eos])
    gen = getattr(model, "generation_config", None)
    if gen is not None and gen.eos_token_id is not None:
        g = gen.eos_token_id
        ids |= set(g if isinstance(g, (list, tuple)) else [g])
    return sorted(int(i) for i in ids if i is not None)


def generate_package(session, request, head, sep, max_new, deadline) -> dict:
    """Greedy generation through ``FocusSession.generate``; ``max_time`` bounds the
    call and a wall-clock overrun is a terminal timeout (Exp 4 amendment 2)."""
    started = time.monotonic()
    session.generate(
        request,
        head=head,
        separator=sep,
        max_new_tokens=max_new,
        max_time=deadline,
    )
    seconds = time.monotonic() - started
    raw = list(session.last["generated_token_ids"])
    stops = set(eos_ids(session.model))
    ended_by_eos = bool(raw) and raw[-1] in stops
    ids = raw[:-1] if ended_by_eos else list(raw)
    truncated = len(ids) >= max_new
    # A call that stopped on ``max_time`` (neither EOS nor the cap) is a timeout even
    # if the wall clock reads a hair under the deadline (registration: terminal).
    timed_out = seconds > deadline or (not ended_by_eos and not truncated)
    termination = "timeout" if timed_out else ("cap" if truncated else "eos")
    return {
        "text": session.decode(ids),
        "generated_token_ids": ids,
        "generated_token_ids_raw": raw,
        "eos_token_ids": sorted(stops),
        "prompt_tokens": session.last["prompt_tokens"],
        "n_generated": len(ids),
        "timed_out": timed_out,
        "truncated": truncated,
        "termination": termination,
        "seconds": seconds,
    }


def load_package(hub: Path):
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(hub)
    model = AutoModelForCausalLM.from_pretrained(
        hub, trust_remote_code=True, dtype=torch.bfloat16, device_map="cuda"
    )
    model.eval()
    return model, tokenizer


def attempt(out_dir: Path, payload: dict) -> None:
    with (out_dir / "attempts.jsonl").open("a") as f:
        f.write(json.dumps(payload) + "\n")
        f.flush()
        os.fsync(f.fileno())


def interrupted_seconds(out_dir: Path, deadline: float = screen.DEADLINE) -> float:
    """Seconds spent in attempts that started but never ended (killed slices),
    reconstructed from attempts.jsonl start/end pairs; a start still open at the end
    of the log counts the full deadline (registration: every attempt counts)."""
    log = out_dir / "attempts.jsonl"
    if not log.exists():
        return 0.0
    open_starts: dict[tuple, float] = {}
    lost = 0.0
    rows = [json.loads(line) for line in log.read_text().splitlines() if line.strip()]
    for row in rows:
        key = (row["id"], row["arm"])
        if row["event"] == "start":
            if key in open_starts:
                lost += min(max(row["monotonic"] - open_starts[key], 0.0), deadline)
            open_starts[key] = row["monotonic"]
        elif row["event"] == "end":
            open_starts.pop(key, None)
    lost += deadline * len(open_starts)
    return lost


def build_arm(model, tokenizer, mc, dialogue, item, arm, research_base, max_new):
    """Build the prompt for one arm through the package and assert the paired
    equality (both arms == research base count) and the 4,096-token allocation."""
    query = item["queries"][0]
    head, sep, request = mc.long_request(dialogue, query)
    session = model.new_session(tokenizer, stencil_focus=(arm == "focus"))
    for role, text, rendered in mc.focus_session_messages(dialogue, item["session"]):
        session.add_message(role, text, rendered=rendered)
    prompt = session.build_prompt(request, head=head, separator=sep)
    built = dict(session.last)
    if built["prompt_tokens"] != research_base:
        raise SystemExit(
            f"item {item['id']} arm {arm}: package prompt {built['prompt_tokens']} "
            f"tokens != research base {research_base}"
        )
    if built["prompt_tokens"] + max_new > 4096:
        raise SystemExit(f"item {item['id']}: prompt + output exceeds 4096 tokens")
    return session, prompt, built, (head, sep, request)


def run(args) -> None:
    from stencil import memorycode as mc

    hub = Path(args.hub)
    root = screen.OUT_LONG
    items_path = Path(args.items_file)
    frozen = json.loads(items_path.read_text())
    items = frozen["items"]
    args.cohort = "long"
    args.policy = "role_evicted"
    args.window = mc.WINDOW
    args.runtime = "package"
    args.split = args.split or items[0]["split"]
    manifest = package_manifest(args, root, hub, items_path)
    manifest["budget_tokens"] = mc.BUDGET
    out_dir = screen._out_dir(args)
    out_dir.mkdir(parents=True, exist_ok=True)
    compute_score = mc.vendored_checker()
    research_tokenizer = screen._tokenizer()
    if args.ids:
        items = [it for it in items if it["id"] in set(args.ids)]
    started = time.monotonic()
    model = tokenizer = None
    for index, item in enumerate(items):
        path = out_dir / f"item-{item['id']}.json"
        record = None
        if path.exists():
            record = json.loads(path.read_text())
            if not record_matches(record, manifest):
                raise SystemExit(f"{path}: record made under another configuration")
        # alternate off-first / on-first by candidate index (registration)
        order = ["base", "focus"]
        if item.get("candidate_index", index) % 2 == 1:
            order = ["focus", "base"]
        missing = [
            a
            for a in order
            if a in args.arms and (not record or a not in record["arms"])
        ]
        if not missing:
            continue
        if args.ceiling_seconds:
            spent = screen._generation_seconds(out_dir, args.arms)
            spent += interrupted_seconds(out_dir, args.deadline)
            if (
                spent >= args.ceiling_seconds
                or screen._ceiling_marker(out_dir).exists()
            ):
                screen._write_atomic(
                    screen._ceiling_marker(out_dir),
                    {
                        "cumulative_generation_seconds": spent,
                        "ceiling_seconds": args.ceiling_seconds,
                        "arms": list(args.arms),
                        "stopped_before_item": item["id"],
                        "utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    },
                )
                print(f"stopping: ceiling {args.ceiling_seconds:.1f} s reached")
                break
        elapsed_min = (time.monotonic() - started) / 60
        needed_min = len(missing) * args.deadline / 60
        if args.budget_minutes and elapsed_min >= args.budget_minutes - needed_min:
            print(f"stopping: {elapsed_min:.1f} min elapsed of {args.budget_minutes}")
            break
        if model is None:
            model, tokenizer = load_package(hub)
            manifest["environment"]["attn_implementation"] = getattr(
                model.config, "_attn_implementation", None
            )
            manifest["eos_token_ids"] = eos_ids(model)
        dialogue = mc.load_dialogue(item["dialogue"])
        query = item["queries"][0]
        research_base = mc.build_long_prompt(
            dialogue, item["session"], query, research_tokenizer, ""
        )["prompt_tokens"]
        if record is None:
            record = {
                "id": item["id"],
                "split": item["split"],
                "model": args.model,
                "candidate_index": item.get("candidate_index"),
                "source": item.get("source"),
                "session": item["session"],
                "queries": item["queries"],
                "history_regex": item["history_regex"],
                "manifest": manifest,
                "arms": {},
            }
        record["manifest"] = manifest
        for arm in missing:
            session, prompt, built, (head, sep, request) = build_arm(
                model, tokenizer, mc, dialogue, item, arm, research_base, args.max_new
            )
            attempt(
                out_dir,
                {
                    "id": item["id"],
                    "arm": arm,
                    "event": "start",
                    "utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "monotonic": time.monotonic(),
                },
            )
            gen = generate_package(
                session, request, head, sep, args.max_new, args.deadline
            )
            attempt(
                out_dir,
                {
                    "id": item["id"],
                    "arm": arm,
                    "event": "end",
                    "seconds": gen["seconds"],
                    "termination": gen["termination"],
                    "monotonic": time.monotonic(),
                },
            )
            gen["query"] = query
            gen["prompt"] = prompt
            gen["prompt_sha256"] = hashlib.sha256(prompt.encode()).hexdigest()
            prompt_ids = session.encode(prompt)
            gen["prompt_ids_sha256"] = hashlib.sha256(
                json.dumps(prompt_ids).encode()
            ).hexdigest()
            gen["window"] = {
                k: v
                for k, v in built.items()
                if k not in ("prompt", "thread_text_kept", "generated_token_ids")
            }
            gen["failures"] = mc.output_failures(
                gen["text"],
                gen["generated_token_ids"],
                gen["truncated"],
                gen["timed_out"],
            )
            gen["scores"] = mc.score_generation(
                gen["text"],
                item["history_regex"],
                compute_score,
                required=item["required"][query],
                structure=item["structure"][query],
            )
            if gen["timed_out"]:
                gen["scores"]["strict"] = False
                if gen["scores"].get("fraction_required") is not None:
                    gen["scores"]["fraction_required"] = 0.0
            reminder = built.get("reminder", "")
            record["arms"][arm] = {
                "policy": "role_evicted" if arm == "focus" else None,
                "selected_sentences": built.get("evicted_sentences", 0),
                "kept_sentences": built.get("kept_sentences", 0),
                "reminder": reminder,
                "reminder_tokens": built.get("reminder_tokens", 0),
                "reminder_empty": not reminder,
                "generations": [gen],
                "strict": gen["scores"]["strict"],
                "fraction": gen["scores"]["fraction"],
            }
            print(
                f"{item['id']} {arm}: strict={gen['scores']['strict']} "
                f"frac_req={gen['scores']['fraction_required']} "
                f"tokens={built.get('reminder_tokens', 0)} end={gen['termination']} "
                f"{gen['seconds']:.1f}s",
                flush=True,
            )
            screen._write_atomic(path, record)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--items-file",
        default=str(ROOT / "results/memorycode-long/items-4c.json"),
        help="frozen item manifest (items-4c.json)",
    )
    parser.add_argument("--split", default=None, help="override the manifest split")
    parser.add_argument("--model", choices=["1.7b", "4b"], default="4b")
    parser.add_argument(
        "--hub", default=str(ROOT / "deploy/stencil_focus/build/hub-4b")
    )
    parser.add_argument("--arms", nargs="+", default=["base", "focus"])
    parser.add_argument("--ids", nargs="+", default=None)
    parser.add_argument("--max-new", type=int, default=screen.MAX_NEW)
    parser.add_argument("--deadline", type=float, default=screen.DEADLINE)
    parser.add_argument("--budget-minutes", type=float, default=0.0)
    parser.add_argument("--ceiling-seconds", type=float, default=0.0)
    args = parser.parse_args(argv)
    run(args)
    return 0


if __name__ == "__main__":
    sys.exit(main())
