"""Generate LONG-cohort records THROUGH THE PUBLISHED PACKAGE (transformers path).

Exp 4C (results/memorycode-long/REGISTRATION-4C.md; Astra implementation review
results/reviews/2026-09-12-exp4c-impl-review-astra.md applied): every prompt is built
by the package's own ``FocusSession`` (flag on = ``focus``, flag off = ``base``) and
every output is generated by the package's ``transformers`` path.

Evidence discipline (review findings 1, 3, 4, 6, 10):
- the package's EFFECTIVE EOS setting (``model.config.eos_token_id``, what the
  package passes to ``generate``) is recorded, frozen in the fingerprint and the only
  terminal token stripped from raw output;
- the complete generation identity (per-file package hashes incl. remote code,
  checker hashes, torch/transformers/tokenizers versions, GPU, dtype, attention
  backend, determinism/TF32/SDPA settings) is compared STRICTLY against the
  qualification manifest after the model is loaded and stored per ARM;
- every generation is an ATTEMPT with a unique id: start row, raw output saved
  durably right after the call, end row, then scoring; accounting is derived from
  the attempt log and per-process heartbeat receipts (interrupted work bounded by
  the last heartbeat), never from terminal records alone;
- allowances (generation ceiling 3 t_max N, resident overhead, per-process limit)
  are checked immediately before each call and enforced by an owned-process
  watchdog thread that ends the process when a limit is crossed;
- reminder provenance: source character spans in the thread, the eviction boundary
  and a thread digest, so identical sentences remain distinguishable.

The runner selects the next missing work in the frozen schedule itself (no
``--ids``/``--arms`` overrides). Records go to
results/memorycode-long/screen_long_4c-4b-package-role_evicted/.
"""

from __future__ import annotations

import argparse
import gc
import hashlib
import importlib.util
import json
import os
import sys
import threading
import time
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))


def _load_script(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


screen = _load_script("memorycode_screen")
items4c = _load_script("memorycode_4c_items")

OUT = ROOT / "results" / "memorycode-long"
FINGERPRINT_KEYS = (
    "model",
    "policy",
    "decoding",
    "window",
    "budget_tokens",
    "items_sha256",
    "package_sha256",
    "checker_sha256",
    "generation_path",
    "eos_token_ids",
    "environment",
)
# resolved only once a model is loaded; None is tolerated ONLY in a provisional match
LOAD_RESOLVED_ENV = ("attn_implementation", "dtype", "device", "gpu_name")
REQUIRED_ENV = (
    "python",
    "torch",
    "transformers",
    "tokenizers",
    "cuda",
    "gpu_name",
    "dtype",
    "device",
    "attn_implementation",
    "deterministic_algorithms",
    "cublas_workspace_config",
    "allow_tf32_matmul",
    "float32_matmul_precision",
    "sdpa_kernels",
)
SKIP_FILES = {"README.md"}
SKIP_DIRS = {"__pycache__", ".git"}
CHECKER_FILES = (
    "src/stencil/memorycode.py",
    "vendor/memorycode/code/evaluate_model_output.py",
)
# registered allowances (REGISTRATION-4C.md, Budget)
QUALIFICATION_ALLOWANCE = 3600.0
OVERHEAD_ALLOWANCE = 2700.0
VERIFICATION_ALLOWANCE = 900.0
BEAT_INTERVAL = 5.0
CALL_GRACE = 60.0  # hard watchdog on one call: deadline + grace
PERSIST_MARGIN = 30.0  # time kept for terminal persistence before a slice limit


# ------------------------------------------------------------------ identities
def package_files(hub: Path) -> dict[str, str]:
    """Per-file SHA-256 of everything that defines the artifact (weights, index,
    config, tokenizer files, remote-code modules), RECURSIVE over the hub directory;
    README.md and cache directories excluded."""
    out = {}
    for p in sorted(hub.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(hub)
        if rel.name in SKIP_FILES or set(rel.parts[:-1]) & SKIP_DIRS:
            continue
        out[rel.as_posix()] = screen._sha256(p)
    return out


def package_fingerprint(files: dict[str, str]) -> str:
    h = hashlib.sha256()
    for name in sorted(files):
        h.update(f"{name}\n{files[name]}\n".encode())
    return h.hexdigest()


def checker_hashes() -> dict[str, str]:
    return {f: screen._sha256(ROOT / f) for f in CHECKER_FILES}


def environment(model=None) -> dict:
    import tokenizers
    import torch
    import transformers

    env = {
        "python": sys.version.split()[0],
        "torch": torch.__version__,
        "transformers": transformers.__version__,
        "tokenizers": tokenizers.__version__,
        "cuda": torch.version.cuda,
        "gpu_name": torch.cuda.get_device_name(0)
        if torch.cuda.is_available()
        else None,
        "dtype": None,
        "device": None,
        "attn_implementation": None,
        "deterministic_algorithms": torch.are_deterministic_algorithms_enabled(),
        "cublas_workspace_config": os.environ.get("CUBLAS_WORKSPACE_CONFIG"),
        "allow_tf32_matmul": torch.backends.cuda.matmul.allow_tf32,
        "float32_matmul_precision": torch.get_float32_matmul_precision(),
        "sdpa_kernels": {
            "flash": torch.backends.cuda.flash_sdp_enabled(),
            "mem_efficient": torch.backends.cuda.mem_efficient_sdp_enabled(),
            "math": torch.backends.cuda.math_sdp_enabled(),
            "cudnn": torch.backends.cuda.cudnn_sdp_enabled(),
        },
    }
    if model is not None:
        env["dtype"] = str(model.dtype)
        env["device"] = str(model.device)
        env["attn_implementation"] = getattr(model.config, "_attn_implementation", None)
    return env


def eos_ids(model) -> list[int]:
    """The package's EFFECTIVE EOS set: ``FocusSession.generate`` passes
    ``model.config.eos_token_id`` to ``generate`` (review finding 1); the
    generation_config list is NOT what stops the package."""
    eos = model.config.eos_token_id
    ids = list(eos) if isinstance(eos, (list, tuple)) else [eos]
    return sorted({int(i) for i in ids if i is not None})


def generation_settings(max_new: int, deadline: float, eos: list[int] | None) -> dict:
    return {
        "greedy": True,
        "do_sample": False,
        "num_beams": 1,
        "max_new": max_new,
        "deadline": deadline,
        "eos_token_id": eos,
    }


def package_manifest(args, hub: Path, items_path: Path | None, model=None) -> dict:
    files = package_files(hub)
    eos = eos_ids(model) if model is not None else None
    return {
        "git_sha": screen._git_sha(),
        "model": args.model,
        "policy": "role_evicted",
        "decoding": generation_settings(args.max_new, args.deadline, eos),
        "window": args.window,
        "budget_tokens": args.budget_tokens,
        "items_file": str(items_path) if items_path else None,
        "items_sha256": screen._sha256(items_path) if items_path else None,
        "generation_path": "transformers",
        "package_dir": str(hub),
        "package_files": files,
        "package_sha256": package_fingerprint(files),
        "tokenizer_sha256": files.get("tokenizer.json"),
        "weights_sha256": [
            files[n] for n in sorted(files) if n.endswith(".safetensors")
        ],
        "checker_sha256": checker_hashes(),
        "eos_token_ids": eos,
        "environment": environment(model),
    }


def fingerprint_matches(a: dict, b: dict, provisional: bool = False) -> bool:
    """STRICT equality of every registered fingerprint key (review finding 6). A
    provisional match, used only to decide whether loading is worthwhile, tolerates
    the load-resolved fields (attention backend, dtype, device, gpu, EOS) being
    unresolved (None) on either side; nothing else is tolerated."""
    for k in FINGERPRINT_KEYS:
        if k == "environment":
            ea, eb = a.get(k) or {}, b.get(k) or {}
            for kk in REQUIRED_ENV:
                if kk not in ea or kk not in eb:
                    if provisional and kk in LOAD_RESOLVED_ENV:
                        continue
                    return False
                if kk in LOAD_RESOLVED_ENV and (ea[kk] is None or eb[kk] is None):
                    if provisional:
                        continue
                    return False
                if ea[kk] != eb[kk]:
                    return False
        elif k in ("eos_token_ids", "decoding"):
            va, vb = a.get(k), b.get(k)
            if provisional:
                va = _without_eos(va)
                vb = _without_eos(vb)
            if va != vb or va is None:
                return False
        elif a.get(k) != b.get(k) or a.get(k) is None:
            return False
    return True


def _without_eos(v):
    if isinstance(v, dict):
        return {kk: vv for kk, vv in v.items() if kk != "eos_token_id"}
    return "unresolved"


# ------------------------------------------------------------------ generation
def generate_package(session, request, head, sep, max_new, deadline) -> dict:
    """Greedy generation through ``FocusSession.generate``; ``max_time`` bounds the
    call. Only a TERMINAL effective EOS is stripped from the raw ids."""
    started = time.monotonic()
    session.generate(
        request,
        head=head,
        separator=sep,
        max_new_tokens=max_new,
        max_time=deadline,
    )
    seconds = time.monotonic() - started
    raw = list(session.last["generated_token_ids"])
    stops = eos_ids(session.model)
    ended_by_eos = bool(raw) and raw[-1] in stops
    ids = raw[:-1] if ended_by_eos else list(raw)
    truncated = (not ended_by_eos) and len(raw) >= max_new
    # A call that stopped on ``max_time`` (neither EOS nor the cap) is a timeout even
    # if the wall clock reads a hair under the deadline (registration: terminal).
    if seconds > deadline:
        timeout_reason = "wall_deadline_exceeded"
    elif not ended_by_eos and not truncated:
        timeout_reason = "max_time_stop"
    else:
        timeout_reason = None
    timed_out = timeout_reason is not None
    termination = "timeout" if timed_out else ("cap" if truncated else "eos")
    return {
        "text": session.tokenizer.decode(ids, skip_special_tokens=True),
        "generated_token_ids": ids,
        "generated_token_ids_raw": raw,
        "eos_token_ids": stops,
        "ended_by_eos": ended_by_eos,
        "prompt_tokens": session.last["prompt_tokens"],
        "n_generated": len(ids),
        "n_generated_raw": len(raw),
        "timed_out": timed_out,
        "timeout_reason": timeout_reason,
        "truncated": truncated,
        "termination": termination,
        "seconds": seconds,
    }


def load_package(hub: Path):
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(hub)
    model = AutoModelForCausalLM.from_pretrained(
        hub, trust_remote_code=True, dtype=torch.bfloat16, device_map="cuda"
    )
    model.eval()
    return model, tokenizer


def release_model(*objs) -> None:
    """Drop the caller's references and empty the CUDA cache (finding 2)."""
    del objs
    gc.collect()
    try:
        import torch

        torch.cuda.empty_cache()
    except Exception:  # pragma: no cover - CPU-only test hosts
        pass


def build_arm(model, tokenizer, mc, dialogue, item, arm, research_base, max_new):
    """Build the prompt for one arm through the package and assert the paired
    equality (both arms == research base count) and the 4,096-token allocation."""
    query = item["queries"][0]
    head, sep, request = mc.long_request(dialogue, query)
    session = model.new_session(tokenizer, stencil_focus=(arm == "focus"))
    for role, text, rendered in mc.focus_session_messages(dialogue, item["session"]):
        session.add_message(role, text, rendered=rendered)
    prompt = session.build_prompt(request, head=head, separator=sep)
    built = dict(session.last)
    if built["prompt_tokens"] != research_base:
        raise SystemExit(
            f"item {item['id']} arm {arm}: package prompt {built['prompt_tokens']} "
            f"tokens != research base {research_base}"
        )
    if built["prompt_tokens"] + max_new > 4096:
        raise SystemExit(f"item {item['id']}: prompt + output exceeds 4096 tokens")
    return session, prompt, built, (head, sep, request)


def reminder_sources(session, built: dict, head: str, sep: str, request: str) -> dict:
    """Provenance of the rendered reminder (finding 10; result-audit finding 1): the
    package selects evicted sentences against the BASE-window boundary (the plain
    window's cut, ``focus_session.build_prompt``), so the boundary is recomputed from
    the base fit, not from the shortened focus window. Records absolute character
    spans of the kept sentences in the thread, their message index, the boundary and a
    digest of the thread text; the kept spans must reproduce the reminder lines."""
    thread = session.thread()
    base = session._fit(head, thread, sep, "", request)
    cut = max(len(thread) - len(base["thread_text_kept"]), 0)
    # message index of every instruction span (same offset arithmetic as the package)
    bounds = []
    offset = 0
    for mi, m in enumerate(session.messages):
        bounds.append((offset, offset + len(m["rendered"]), mi))
        offset += len(m["rendered"])
    spans = []
    for start, end, sentence in session.instruction_spans():
        mi = next(i for (lo, hi, i) in bounds if lo <= start < hi)
        spans.append((start, end, mi, sentence))
    spans = sorted(set(spans))
    evicted = [s for s in spans if s[1] <= cut]
    k = built.get("kept_sentences", 0) or 0
    kept = evicted[-k:] if k else []
    reminder = built.get("reminder", "")
    lines = reminder.split("\n")[1:] if reminder else []
    if [f"- {txt}" for _, _, _, txt in kept] != lines:
        raise SystemExit("reminder provenance does not reproduce the reminder")
    return {
        "thread_chars": len(thread),
        "thread_sha256": hashlib.sha256(thread.encode()).hexdigest(),
        "eviction_boundary_char": cut,
        "evicted_spans": len(evicted),
        "kept_spans": [
            {"start": s, "end": e, "message_index": mi, "sentence": txt}
            for s, e, mi, txt in kept
        ],
    }


# ------------------------------------------------------------------ receipts
class ProcessReceipt:
    """Durable heartbeat receipt for one owned GPU process plus the watchdog that
    ends the process when a registered limit is crossed (finding 3).

    ``<dir>/process-<utc>-<pid>.json`` is rewritten every ``BEAT_INTERVAL`` seconds
    with the elapsed resident time; a process that dies leaves ``ended`` null, and
    its resident time is bounded above by the last beat plus one interval.
    """

    def __init__(
        self,
        out_dir: Path,
        kind: str,
        resident_limit: float | None,
        overhead_limit: float | None = None,
        prior_overhead: float = 0.0,
        call_limit: float | None = None,
    ) -> None:
        self.dir = Path(out_dir)
        self.dir.mkdir(parents=True, exist_ok=True)
        self.kind = kind
        self.pid = os.getpid()
        self.started_utc = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        self.path = self.dir / f"process-{self.started_utc}-{self.pid}.json"
        self.t0 = time.monotonic()
        self.resident_limit = resident_limit
        self.overhead_limit = overhead_limit
        self.prior_overhead = prior_overhead
        self.call_limit = call_limit
        self.generation_seconds = 0.0
        self.call_started: float | None = None
        self.ended: str | None = None
        self._lock = threading.Lock()
        self._stop = threading.Event()
        self.write()
        self._thread = threading.Thread(target=self._beat, daemon=True)
        self._thread.start()

    def elapsed(self) -> float:
        return time.monotonic() - self.t0

    def overhead(self) -> float:
        cur = (
            self.elapsed() - self.call_started if self.call_started is not None else 0.0
        )
        return self.elapsed() - self.generation_seconds - cur

    def payload(self) -> dict:
        return {
            "kind": self.kind,
            "pid": self.pid,
            "started_utc": self.started_utc,
            "elapsed": self.elapsed(),
            "last_beat_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "beat_interval": BEAT_INTERVAL,
            "generation_seconds": self.generation_seconds,
            "current_call_started": self.call_started,
            "overhead_seconds": self.overhead(),
            "limits": {
                "resident": self.resident_limit,
                "overhead_cumulative": self.overhead_limit,
                "call": self.call_limit,
            },
            "ended": self.ended,
        }

    def write(self) -> None:
        with self._lock:
            screen._write_atomic(self.path, self.payload())

    def _violation(self) -> str | None:
        if self.resident_limit is not None and self.elapsed() > self.resident_limit:
            return "watchdog:resident"
        if (
            self.overhead_limit is not None
            and self.prior_overhead + self.overhead() > self.overhead_limit
        ):
            return "watchdog:overhead"
        if (
            self.call_limit is not None
            and self.call_started is not None
            and self.elapsed() - self.call_started > self.call_limit
        ):
            return "watchdog:call"
        return None

    def _beat(self) -> None:
        while not self._stop.wait(BEAT_INTERVAL):
            why = self._violation()
            if why:
                self.ended = why
                self.write()
                print(f"{why}: ending process {self.pid}", flush=True)
                os._exit(3)
            self.write()

    def begin_call(self) -> float:
        self.call_started = self.elapsed()
        self.write()
        return self.call_started

    def end_call(self, seconds: float) -> None:
        self.generation_seconds += seconds
        self.call_started = None
        self.write()

    def finish(self, how: str = "clean") -> None:
        self._stop.set()
        self.ended = how
        self.write()


def process_receipts(out_dir: Path) -> list[dict]:
    rows = []
    for p in sorted(Path(out_dir).glob("process-*.json")):
        try:
            row = json.loads(p.read_text())
        except json.JSONDecodeError:
            row = {"malformed": True, "elapsed": None, "ended": None}
        row["file"] = p.name
        rows.append(row)
    return rows


def resident_seconds(out_dir: Path) -> dict:
    """Resident time over every process receipt; a receipt without ``ended`` is
    bounded by its last beat plus one interval and counted as interrupted."""
    total = overhead = gen = 0.0
    open_count = 0
    unbounded = False
    for r in process_receipts(out_dir):
        if r.get("malformed") or r.get("elapsed") is None:
            unbounded = True
            continue
        bound = float(r["elapsed"])
        if not r.get("ended"):
            bound += float(r.get("beat_interval", BEAT_INTERVAL))
            open_count += 1
        total += bound
        gen += float(r.get("generation_seconds", 0.0))
        overhead += float(r.get("overhead_seconds", 0.0))
    return {
        "resident_seconds": total,
        "overhead_seconds": overhead,
        "generation_seconds_in_receipts": gen,
        "processes": len(process_receipts(out_dir)),
        "interrupted_processes": open_count,
        "unbounded": unbounded,
    }


def attempt(out_dir: Path, payload: dict) -> None:
    with (out_dir / "attempts.jsonl").open("a") as f:
        f.write(json.dumps(payload) + "\n")
        f.flush()
        os.fsync(f.fileno())


def attempt_rows(out_dir: Path) -> list[dict]:
    log = Path(out_dir) / "attempts.jsonl"
    if not log.exists():
        return []
    rows = []
    for line in log.read_text().splitlines():
        if line.strip():
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                rows.append({"event": "malformed"})
    return rows


def attempt_accounting(out_dir: Path, deadline: float = screen.DEADLINE) -> dict:
    """Generation spending derived from the attempt log alone (finding 4): every
    ended attempt counts its measured seconds exactly once (scored or not); an open
    attempt counts the time until its process's last heartbeat plus one interval;
    an open attempt whose process receipt is missing is UNBOUNDED (the summary
    cannot establish budget compliance)."""
    receipts = {r["file"]: r for r in process_receipts(out_dir)}
    started: dict[str, dict] = {}
    completed = 0.0
    n_completed = 0
    open_seconds = 0.0
    n_open = 0
    unbounded = False
    for row in attempt_rows(out_dir):
        ev = row.get("event")
        if ev == "start":
            started[row["attempt_id"]] = row
        elif ev == "end":
            started.pop(row["attempt_id"], None)
            completed += float(row["seconds"])
            n_completed += 1
        else:
            unbounded = True
    for row in started.values():
        n_open += 1
        rec = receipts.get(row.get("process"))
        if rec is None or rec.get("elapsed") is None:
            unbounded = True
            open_seconds += deadline + CALL_GRACE
            continue
        bound = float(rec["elapsed"]) + (
            0.0 if rec.get("ended") else float(rec.get("beat_interval", BEAT_INTERVAL))
        )
        open_seconds += max(bound - float(row["process_elapsed"]), 0.0)
    return {
        "completed_seconds": completed,
        "n_completed": n_completed,
        "open_seconds": open_seconds,
        "n_open": n_open,
        "unbounded": unbounded,
        "generation_seconds": completed + open_seconds,
    }


def ended_attempts(out_dir: Path) -> dict[tuple[str, str], list[dict]]:
    """Ended attempts by (id, arm) with their raw-output file (resume scoring)."""
    out: dict[tuple[str, str], list[dict]] = {}
    for row in attempt_rows(out_dir):
        if row.get("event") == "end":
            out.setdefault((row["id"], row["arm"]), []).append(row)
    return out


def raw_path(out_dir: Path, attempt_id: str) -> Path:
    return Path(out_dir) / "raw" / f"{attempt_id.replace(':', '_')}.json"


# ------------------------------------------------------------------ scoring
def score_raw(raw: dict, item: dict, mc, compute_score) -> dict:
    """Score a saved raw output with the frozen checker (idempotent; used at
    generation time and to resume after a post-generation interruption)."""
    gen = dict(raw["generation"])
    query = item["queries"][0]
    gen["failures"] = mc.output_failures(
        gen["text"], gen["generated_token_ids"], gen["truncated"], gen["timed_out"]
    )
    gen["scores"] = mc.score_generation(
        gen["text"],
        item["history_regex"],
        compute_score,
        required=item["required"][query],
        structure=item["structure"][query],
    )
    if gen["timed_out"]:
        gen["scores"]["strict"] = False
        if gen["scores"].get("fraction_required") is not None:
            gen["scores"]["fraction_required"] = 0.0
    return gen


def arm_record(raw: dict, gen: dict) -> dict:
    built = raw["window"]
    reminder = built.get("reminder", "")
    return {
        "attempt_id": raw["attempt_id"],
        "raw_file": raw["raw_file"],
        "policy": "role_evicted" if raw["arm"] == "focus" else None,
        "selected_sentences": built.get("evicted_sentences", 0),
        "kept_sentences": built.get("kept_sentences", 0),
        "reminder": reminder,
        "reminder_tokens": built.get("reminder_tokens", 0),
        "reminder_empty": not reminder,
        "reminder_sources": raw.get("reminder_sources"),
        "generations": [gen],
        "strict": gen["scores"]["strict"],
        "fraction": gen["scores"]["fraction"],
        "manifest": raw["manifest"],
    }


# ------------------------------------------------------------------ run
def frozen_chain(items_path: Path, qualification_path: Path) -> dict:
    """Load and verify the freeze chain (finding 5) or exit."""
    frozen = json.loads(items_path.read_text())
    qual = json.loads(qualification_path.read_text())
    problems = items4c.verify_frozen(frozen, qual, screen._sha256(qualification_path))
    if problems:
        raise SystemExit("frozen manifest chain broken: " + "; ".join(problems))
    return {"frozen": frozen, "qualification": qual}


def run(args) -> int:
    from stencil import memorycode as mc

    hub = Path(args.hub)
    items_path = Path(args.items_file)
    chain = frozen_chain(items_path, Path(args.qualification))
    frozen, qual = chain["frozen"], chain["qualification"]
    items = frozen["items"]
    expect = qual["manifest"]
    args.model = expect["model"]
    args.window = mc.WINDOW
    args.budget_tokens = mc.BUDGET
    args.max_new = expect["decoding"]["max_new"]
    args.deadline = expect["decoding"]["deadline"]
    args.cohort, args.policy, args.runtime = "long", "role_evicted", "package"
    args.split = items[0]["split"]
    out_dir = screen._out_dir(args)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "raw").mkdir(exist_ok=True)
    provisional = package_manifest(args, hub, items_path)
    provisional["items_sha256"] = screen._sha256(items_path)
    expect_items = dict(expect, items_sha256=provisional["items_sha256"])
    if not fingerprint_matches(provisional, expect_items, provisional=True):
        raise SystemExit("package/environment differs from the qualification manifest")
    ceiling = 3.0 * frozen["t_max_seconds"] * frozen["n"]
    compute_score = mc.vendored_checker()
    research_tokenizer = screen._tokenizer()
    prior = resident_seconds(out_dir)
    receipt = ProcessReceipt(
        out_dir,
        "evaluation",
        resident_limit=args.resident_limit or None,
        overhead_limit=OVERHEAD_ALLOWANCE,
        prior_overhead=prior["overhead_seconds"],
        call_limit=args.deadline + CALL_GRACE,
    )
    model = tokenizer = None
    manifest = None
    ended = ended_attempts(out_dir)
    try:
        for item in items:
            path = out_dir / f"item-{item['id']}.json"
            record = json.loads(path.read_text()) if path.exists() else None
            order = ["base", "focus"]
            if item["candidate_index"] % 2 == 1:
                order = ["focus", "base"]
            for arm in order:
                if record and arm in record["arms"]:
                    continue
                if record is None:
                    record = {
                        "id": item["id"],
                        "split": item["split"],
                        "model": args.model,
                        "candidate_index": item["candidate_index"],
                        "source": item.get("source"),
                        "session": item["session"],
                        "queries": item["queries"],
                        "history_regex": item["history_regex"],
                        "arms": {},
                    }
                # resume scoring from a durable raw output (finding 4)
                saved = [
                    r
                    for r in ended.get((item["id"], arm), [])
                    if raw_path(out_dir, r["attempt_id"]).exists()
                ]
                if saved:
                    raw = json.loads(
                        raw_path(out_dir, saved[-1]["attempt_id"]).read_text()
                    )
                    if not fingerprint_matches(raw["manifest"], expect_items):
                        raise SystemExit(
                            f"{item['id']} {arm}: raw output under another identity"
                        )
                    record["arms"][arm] = arm_record(
                        raw, score_raw(raw, item, mc, compute_score)
                    )
                    record.setdefault("manifest", raw["manifest"])
                    screen._write_atomic(path, record)
                    print(
                        f"{item['id']} {arm}: scored from saved raw output", flush=True
                    )
                    continue
                # allowances immediately before the call (finding 3)
                acct = attempt_accounting(out_dir, args.deadline)
                if (
                    acct["unbounded"]
                    or acct["generation_seconds"] + args.deadline > ceiling
                ):
                    marker = screen._ceiling_marker(out_dir)
                    if not marker.exists():
                        screen._write_atomic(
                            marker,
                            {
                                "accounting": acct,
                                "ceiling_seconds": ceiling,
                                "stopped_before": [item["id"], arm],
                                "utc": time.strftime(
                                    "%Y-%m-%dT%H:%M:%SZ", time.gmtime()
                                ),
                            },
                        )
                    print(
                        f"stopping: ceiling {ceiling:.1f} s would be exceeded",
                        flush=True,
                    )
                    return 0
                if (
                    prior["overhead_seconds"] + receipt.overhead() + PERSIST_MARGIN
                    > OVERHEAD_ALLOWANCE
                ):
                    print("stopping: resident overhead allowance exhausted", flush=True)
                    return 0
                if args.resident_limit and (
                    receipt.elapsed() + args.deadline + CALL_GRACE + PERSIST_MARGIN
                    > args.resident_limit
                ):
                    print("stopping: slice limit reached", flush=True)
                    return 0
                if model is None:
                    model, tokenizer = load_package(hub)
                    manifest = package_manifest(args, hub, items_path, model)
                    if not fingerprint_matches(manifest, expect_items):
                        raise SystemExit(
                            "STRICT fingerprint mismatch after loading; not generating"
                        )
                    for p in out_dir.glob("item-*.json"):
                        old = json.loads(p.read_text())
                        for a, data in old.get("arms", {}).items():
                            if not fingerprint_matches(
                                data.get("manifest") or {}, manifest
                            ):
                                raise SystemExit(
                                    f"{p.name} arm {a}: made under another identity"
                                )
                dialogue = mc.load_dialogue(item["dialogue"])
                research_base = mc.build_long_prompt(
                    dialogue,
                    item["session"],
                    item["queries"][0],
                    research_tokenizer,
                    "",
                )["prompt_tokens"]
                session, prompt, built, (head, sep, request) = build_arm(
                    model,
                    tokenizer,
                    mc,
                    dialogue,
                    item,
                    arm,
                    research_base,
                    args.max_new,
                )
                attempt_id = f"{item['id']}:{arm}:{uuid.uuid4().hex[:12]}"
                attempt(
                    out_dir,
                    {
                        "attempt_id": attempt_id,
                        "id": item["id"],
                        "arm": arm,
                        "event": "start",
                        "utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                        "process": receipt.path.name,
                        "process_elapsed": receipt.begin_call(),
                    },
                )
                gen = generate_package(
                    session, request, head, sep, args.max_new, args.deadline
                )
                receipt.end_call(gen["seconds"])
                prompt_ids = session.encode(prompt)
                raw = {
                    "attempt_id": attempt_id,
                    "raw_file": raw_path(out_dir, attempt_id).name,
                    "id": item["id"],
                    "arm": arm,
                    "query": item["queries"][0],
                    "prompt": prompt,
                    "prompt_sha256": hashlib.sha256(prompt.encode()).hexdigest(),
                    "prompt_ids_sha256": hashlib.sha256(
                        json.dumps(prompt_ids).encode()
                    ).hexdigest(),
                    "prompt_ids_count": len(prompt_ids),
                    "window": {
                        k: v
                        for k, v in built.items()
                        if k not in ("prompt", "thread_text_kept")
                    },
                    "reminder_sources": (
                        reminder_sources(session, built, head, sep, request)
                        if arm == "focus"
                        else None
                    ),
                    "generation": gen,
                    "manifest": manifest,
                    "utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                }
                screen._write_atomic(
                    raw_path(out_dir, attempt_id), raw
                )  # durable first
                attempt(
                    out_dir,
                    {
                        "attempt_id": attempt_id,
                        "id": item["id"],
                        "arm": arm,
                        "event": "end",
                        "seconds": gen["seconds"],
                        "termination": gen["termination"],
                        "raw_file": raw["raw_file"],
                        "process": receipt.path.name,
                        "process_elapsed": receipt.elapsed(),
                    },
                )
                ended.setdefault((item["id"], arm), []).append(
                    {"attempt_id": attempt_id}
                )
                gen = score_raw(raw, item, mc, compute_score)
                record["arms"][arm] = arm_record(raw, gen)
                record.setdefault("manifest", manifest)
                screen._write_atomic(path, record)
                print(
                    f"{item['id']} {arm}: end={gen['termination']} "
                    f"{gen['seconds']:.1f}s raw={gen['n_generated_raw']} "
                    f"reminder_tokens={built.get('reminder_tokens', 0)}",
                    flush=True,
                )
        print("schedule complete", flush=True)
        return 0
    finally:
        receipt.finish()
        if model is not None:
            release_model(model, tokenizer)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--items-file", default=str(OUT / "items-4c.json"))
    parser.add_argument("--qualification", default=str(OUT / "qualification-4c.json"))
    parser.add_argument(
        "--hub", default=str(ROOT / "deploy/stencil_focus/build/hub-4b")
    )
    parser.add_argument(
        "--resident-limit",
        type=float,
        default=0.0,
        help="per-process resident-time limit in seconds (watchdog); 0 = none",
    )
    args = parser.parse_args(argv)
    return run(args)


if __name__ == "__main__":
    sys.exit(main())
